Fix dropdown select in pageTemplatesPane
GoogleForCreators/web-stories-wp pull request #10078
Opened 2021-12-30 11:49 UTC by codingcarrots20

## Context

Fixes dropdown select function in pageTemplatesPane in the library.

## Summary

In the dropdown menu to select what template list ( default or custom ) needs to be shown, selecting the already selected option toggles the selection.

## Relevant Technical Choices

## To-do

## User-facing changes

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Reviews

### Does this PR have a security-related impact?

### Does this PR change what data or activity we track or use?

### Does this PR have a legal-related impact?

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [ ] I have added a matching `Type: XYZ` label to the PR

---

Fixes #10077

2022-01-03 16:04 UTC, BrookeGraham approved these changes

2022-01-03 16:04 UTC, BrookeGraham commented on packages/story-editor/src/components/library/panes/pageTemplates/pageTemplatesPane.js
> +    setShowDefaultTemplates(DEFAULT === menuItem);
Excellent find. Only thing I would suggest would be to not reset `showDefaultTemplates` or `localStore` if the new selection is the same as what is already selected. No need to reset them if they are just gonna be the same. Something like
```
if (showDefaultTemplates !== (DEFAULT === menuItem)) {
...}
```

2022-01-03 16:47 UTC, BrittanyIRL requested changes
Thanks so much for this contribution. I agree with @BrookeGraham 's suggestion to check the values against each other before firing functions.  After you update just tag for re-review.

2022-01-03 16:47 UTC, BrittanyIRL commented on packages/story-editor/src/components/library/panes/pageTemplates/pageTemplatesPane.js
> +  const handleSelect = (event, menuItem) => {
looks like `event` isn't getting used. When targeting the second value passed through we typically do `(_, menuItem)`

2022-01-11 23:42 UTC, BrittanyIRL reviewed
Awesome! thanks for the updates and so sorry for the delayed response. If you would be so kind as to rebase this branch off of `/main` so we can double check that all of the integration tests are still good (they should be), then this will be good to go.

2022-01-12 17:06 UTC, BrittanyIRL approved these changes
thank you so much for the extra hoops to jump through for this. appreciate the fix a lot.  We will send this on to QA and merge once they are through with it.

2022-01-12 17:21 UTC, swissspidy commented
Note that external contributions can't easily be QAed on our env right now due to some limitations. If you have verified that this fixes an actual issue feel free to merge this without another person looking at it.

2022-01-19 09:20 UTC, merged