Dashboard: Responsive Style Updates
GoogleForCreators/web-stories-wp pull request #1091
Opened 2020-04-07 21:08 UTC by BrittanyIRL

2020-04-07 22:26 UTC, BrittanyIRL commented on assets/src/dashboard/app/views/myStories/index.js
> +    margin: ${({ theme }) => `0 ${theme.pageGutter.min}px`};
i didn't feel like we needed 5 pageGutters, so i just did desktop and min, which is a true min. How do you both feel about intermingling the word 'min' like this?

2020-04-08 00:13 UTC, mariano-formidable requested changes
Hmmmm... I'm noticing that we're setting `width` and `height` in a lot of places using similar (or the same) breakpoints, _and_ that we have the `usePagePreviewSize` which also calculates the appropriate `width` and `height` of a card based on the window size... I'm curious if there's a way to use `usePagePreviewSize` to set the `width` and `height` for _all the things_ that need it, and then we can remove a bunch of the media queries we have that implement the same restriction.

I only ask because right now it's possible for our breakpoints and `usePagePreviewSize` to get out of sync.  In fact, I think I found an out-of-sync bug in the current code, in the gif below I'm highlighting the `PreviewPane` container and the `DisplayElement` container and notice how the `PreviewPane` container's width & height (set by media queries) is smaller than the `DisplayElement` container (set by `usePagePreviewSize`).

![iphone_grid](https://user-images.githubusercontent.com/40646372/78730842-d5a4fd80-78f2-11ea-96cf-13e79415c3f5.gif)

Refactoring all the subcomponents to use `usePagePreviewSize` instead of media queries would be a bit of work, and I know you've already put in a lot in this refactor sooooo if it doesn't make sense feel free to push back!

2020-04-08 13:32 UTC, carlos-kelly commented
I agree with Mariano that we likely have to leverage `usePagePreviewSize` since it's the source of truth. But also we will need flexible height for the title and date. Since those can extend a couple of lines depending on the width. I do think it's fine to make that a future PR since this is quite large.

2020-04-08 13:33 UTC, carlos-kelly commented
For mobile I do wonder if it would be better to do the page dropdown + search on the same line.

2020-04-08 13:34 UTC, carloskelly13 approved these changes
I think this moves us in the right direction absent designs, but I do agree with Mariano that we should find a way to leverage the hook that calculates the story width.

2020-04-08 15:05 UTC, BrittanyIRL commented
> Hmmmm... I'm noticing that we're setting `width` and `height` in a lot of places using similar (or the same) breakpoints, _and_ that we have the `usePagePreviewSize` which also calculates the appropriate `width` and `height` of a card based on the window size... I'm curious if there's a way to use `usePagePreviewSize` to set the `width` and `height` for _all the things_ that need it, and then we can remove a bunch of the media queries we have that implement the same restriction.
> 
> I only ask because right now it's possible for our breakpoints and `usePagePreviewSize` to get out of sync. In fact, I think I found an out-of-sync bug in the current code, in the gif below I'm highlighting the `PreviewPane` container and the `DisplayElement` container and notice how the `PreviewPane` container's width & height (set by media queries) is smaller than the `DisplayElement` container (set by `usePagePreviewSize`).
> 
> ![iphone_grid](https://user-images.githubusercontent.com/40646372/78730842-d5a4fd80-78f2-11ea-96cf-13e79415c3f5.gif)
> 
> Refactoring all the subcomponents to use `usePagePreviewSize` instead of media queries would be a bit of work, and I know you've already put in a lot in this refactor sooooo if it doesn't make sense feel free to push back!

What a good find, this rules! I am going to push back just for the sake of review time, clarity, and small(er) PRs and do this as a follow up. It should be done sooner rather than later for sure and I feel like all this clean up is only going to make the other grid views go faster.  That cool with you?

2020-04-08 15:27 UTC, mariano-formidable approved these changes
Great move to resize goodness!

2020-04-08 15:28 UTC, merged