Dashboard: Story Grid Media Query/Resize Clean Up
GoogleForCreators/web-stories-wp pull request #1107
Opened 2020-04-08 18:46 UTC by BrittanyIRL

# Overview
@mariano-formidable pointed out in my prior PR (https://github.com/google/web-stories-wp/pull/1091) that: 
> we're setting width and height in a lot of places using similar (or the same) breakpoints, and that we have the usePagePreviewSize which also calculates the appropriate width and height of a card based on the window size... I'm curious if there's a way to use usePagePreviewSize to set the width and height for all the things that need it, and then we can remove a bunch of the media queries we have that implement the same restriction.

> I only ask because right now it's possible for our breakpoints and usePagePreviewSize to get out of sync. In fact, I think I found an out-of-sync bug in the current code, in the gif below I'm highlighting the PreviewPane container and the DisplayElement container and notice how the PreviewPane container's width & height (set by media queries) is smaller than the DisplayElement container (set by usePagePreviewSize).

And this PR should resolve that discrepancy. 

I was able to shrink the theme to just desired width based on breakpoint, the `usePagePreviewSize` util is doing the work of creating the ratio to display story previews on. This ratio is what we should be basing the parent grid on to ensure consistent display. This also means we can ditch a bunch of media queries. 🎉  

## Testing 
- Play with my stories and make sure it's still collapsing gracefully. 
- Hover over a card and see the new context menu displaying right. 

![samesize](https://user-images.githubusercontent.com/10720454/78821577-91ffd180-798e-11ea-9ca1-e34573b20fdb.gif)

2020-04-08 20:45 UTC, mariano-formidable requested changes
Wow!  On being able to remove so many media queries... awesome! :tada:

I only found one little visual bug, as you grow/shrink the width the grid can fall into states where there is zero space between stories.

This screenshot was set at 832px width (and I saw it happen at 1305px width too):
![image](https://user-images.githubusercontent.com/40646372/78831227-1e65c080-799e-11ea-89f3-197964ffa700.png)

2020-04-08 20:59 UTC, BrittanyIRL commented
> Wow! On being able to remove so many media queries... awesome! 🎉
> 
> I only found one little visual bug, as you grow/shrink the width the grid can fall into states where there is zero space between stories.
> 
> This screenshot was set at 832px width (and I saw it happen at 1305px width too):
> ![image](https://user-images.githubusercontent.com/40646372/78831227-1e65c080-799e-11ea-89f3-197964ffa700.png)

Good call out, swapped margin for column gap and it should work better now :D

2020-04-08 21:17 UTC, mariano-formidable approved these changes
Looks great to me!

2020-04-09 15:25 UTC, carloskelly13 approved these changes
I like this. It really simplifies the calculation of the width.

2020-04-09 15:48 UTC, merged