Settings: Change selected font upon click
GoogleForCreators/web-stories-wp pull request #11194
Opened 2022-04-05 21:09 UTC by timarney

## Context

Clicking an option under Custom Fonts doesn't select the option

## Summary

Adds a onClick hander for font options 

## Relevant Technical Choices

## To-do

## User-facing changes

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Reviews

### Does this PR have a security-related impact?

### Does this PR change what data or activity we track or use?

### Does this PR have a legal-related impact?

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [ ] I have added a matching `Type: XYZ` label to the PR

---

Fixes #

2022-04-07 15:51 UTC, spacedmonkey requested changes
If the font row is clickable, then the cursor should change.

2022-04-07 20:42 UTC, swissspidy commented
> If the font row is clickable, then the cursor should change.

Not sure about that.

The example at https://w3c.github.io/aria-practices/examples/listbox/listbox-scrollable.html also doesn't use a different cursor

2022-04-09 01:08 UTC, timarney commented
> If the font row is clickable, then the cursor should change.

I have no strong opinion on this either way.  Let me know where we want to go with this one.

2022-04-11 11:22 UTC, timarney commented
Noting the e2e is fixed here:

https://github.com/GoogleForCreators/web-stories-wp/pull/11144/files#r847216208

2022-04-11 13:21 UTC, swissspidy approved these changes
This works as expected. Current cursor should be fine.

2022-04-11 13:21 UTC, merged