Changed white-space handling in text elements
GoogleForCreators/web-stories-wp pull request #11262
Opened 2022-04-13 18:41 UTC by barklund

## Summary

This changes how white-space is handled in text elements, as Firefox is unable to make justified text, if white-space is set tp `pre-wrap`. Setting it to `pre-line` does (almost) the same thing while avoiding the bug in Firefox completely.

The main difference between `pre-wrap` and `pre-line` are:

- Multiple white-space characters in a row are collapsed (unless non-breaking).
- Leading white-space is removed (unless non-breaking).

Potential consequences:

- If any text sets use either of the above, they would render wrong. However, both searching as well as manual checking seem to indicate, that no text sets do this.
- If any templates (story and/or page) use either of the above, they would render wrong. It was a lot harder to check these, but it does not appear that any of them use either of the above.
- If a user has a story with multiple spaces or leading space in a line, it could potentially render wrong. However, because our text editor converts all spaces to non-breaking spaces and all tabs (they could be pasted in) to four non-breaking spaces, this is never actually a problem. Multiple spaces manually entered in the editor still render correctly!

## User-facing changes

Various browsers with various text alignment, before and after:

| Browser | Before | After |
|-|-|-|
| Chrome | ![chrome_before](https://user-images.githubusercontent.com/637548/163247462-04ac01ff-5534-4d73-8077-6b2f166d94cc.png) | ![chrome_after](https://user-images.githubusercontent.com/637548/163247476-2d6b114e-16cd-41b7-b274-6b538870b143.png) |
| Safari | ![safari_before](https://user-images.githubusercontent.com/637548/163247521-e6029aba-de1c-4e08-a815-bcefc71e7319.png) | ![safari_after](https://user-images.githubusercontent.com/637548/163247540-4c29b0b7-5e3a-461d-90fb-e01661cf14f9.png) |
| Firefox | ![firefox_before](https://user-images.githubusercontent.com/637548/163247553-485cad6a-e9e8-4030-bd9b-42615d5f591d.png) | ![firefox_after](https://user-images.githubusercontent.com/637548/163247569-8b9751f8-fc65-4488-90e4-9dae21efb727.png) |

## Testing Instructions

This PR can be tested by following these steps:

1.  Pay special attention to Firefox, but test in other browsers too
2. Add a text field and make sure it has multiple lines due to wrapping, not due to manual line-breaks
3. Adjust text alignment to justified
4. Observe that text actually renders justified in both editor and final story
5. Play with multiple spaces, newlines, and leading spaces after a newline and observe, that all white-space renders correctly in both editor and final story

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #10542

2022-04-14 21:06 UTC, merapi reviewed
I'm still checking the impact of this.

Is it just as easy to add this to the rich text editor? To make the display and edit mode look the same.

https://user-images.githubusercontent.com/21036224/163474814-12669509-d31c-4aaa-b4ff-38613e26a608.mov

2022-04-15 16:53 UTC, barklund commented
> I'm still checking the impact of this.

No worries, it's a tiny change with a potential for a lot of consequences! So let's be diligent before merging!

> Is it just as easy to add this to the rich text editor? To make the display and edit mode look the same.

Excellent point, forgot about that!

2022-04-15 17:43 UTC, barklund commented on packages/element-library/src/text/edit.js
> +
@merapi, it wasn't the prettiest fix, but it works consistently.

2022-04-18 20:22 UTC, BrittanyIRL approved these changes, later dismissed
I think this looks good! What an interesting browser difference.

2022-04-20 15:03 UTC, merapi commented
> What an interesting browser difference.

Yeah, browsers are really interesting piece of software 😉 

![image](https://user-images.githubusercontent.com/21036224/164261258-e29ceb1d-b7eb-4948-b1dc-a7e1edea0f3c.png)

2022-04-22 21:17 UTC, merapi requested changes
This is waiting for [UX/product decision](https://xwp.slack.com/archives/CCCAUAH6F/p1650483814965059?thread_ts=1650453276.486579&cid=CCCAUAH6F) due to this bug (removing whitespaces):


https://user-images.githubusercontent.com/21036224/164794608-4d902e85-fbd0-443f-bb14-3cb73a3ea242.mp4

2022-05-24 15:34 UTC, merapi submitted a review, later dismissed

2022-05-25 14:29 UTC, merapi approved these changes

2022-05-25 14:46 UTC, merged