Tracking: Add hardening for user role retrieval
GoogleForCreators/web-stories-wp pull request #11478
Opened 2022-05-12 10:12 UTC by timarney

## Context

## Summary

## Relevant Technical Choices

## To-do

## User-facing changes

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Reviews

### Does this PR have a security-related impact?

### Does this PR change what data or activity we track or use?

### Does this PR have a legal-related impact?

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [ ] I have added a matching `Type: XYZ` label to the PR

---

Fixes #

2022-05-12 13:00 UTC, spacedmonkey commented on includes/Tracking.php
> +		$role        = ! empty( wp_get_current_user()->roles ) && \array_key_exists( 0, wp_get_current_user()->roles ) ? wp_get_current_user()->roles[0] : '';
```suggestion
		$role        = ! empty( wp_get_current_user()->roles ) && is_array( wp_get_current_user()->roles ) ? array_shift( wp_get_current_user()->roles ) : ''; 
```

I prefer to use an array_shift here, over using the first element in an array. This is a little cleaner as well.

2022-05-13 09:36 UTC, spacedmonkey requested changes, later dismissed
Lint error.

2022-05-13 20:34 UTC, timarney commented
>Lint error

Fixed

2022-05-16 09:34 UTC, swissspidy commented
Possible to add a test for this? Otherwise looks good.

2022-05-16 11:37 UTC, timarney commented
> Possible to add a test for this? Otherwise looks good.

Not sure how to mock out the an object with missing index (0) properly 

using the original code  non of these throw 

```php 
$user->roles = array(); 
$user->roles = false; 
$user->roles = ""; 
```

https://developer.wordpress.org/reference/classes/wp_user/

2022-05-16 11:55 UTC, swissspidy commented
This should work:

```php
/**
 * @covers ::get_user_properties
 */
public function test_get_settings_user_malformed_roles(): void {
	$user_id = self::factory()->user->create(
		[
			'role' => 'administrator',
		]
	);

	wp_set_current_user( $user_id );

	global $current_user;
	$current_user->roles = [ 1 => 'administrator' ];

	$this->site_kit->method( 'get_plugin_status' )->willReturn(
		[
			'installed'       => true,
			'active'          => true,
			'analyticsActive' => true,
			'link'            => 'https://example.com',
		]
	);
	$this->experiments->method( 'get_enabled_experiments' )
		->willReturn( [ 'enableFoo', 'enableBar' ] );

	$settings = $this->instance->get_settings();

	$this->assertSame( 'administrator', $settings['userProperties']['userRole'] );
}
```

2022-05-16 12:48 UTC, swissspidy approved these changes

2022-05-16 12:48 UTC, merged