[9248] renaming layers
GoogleForCreators/web-stories-wp pull request #11477
Opened 2022-05-12 07:43 UTC by mariana-k

## Context

## Summary

## Relevant Technical Choices

## To-do

## User-facing changes

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Reviews

### Does this PR have a security-related impact?

### Does this PR change what data or activity we track or use?

### Does this PR have a legal-related impact?

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [ ] I have added a matching `Type: XYZ` label to the PR

---

Fixes #

2022-05-13 02:01 UTC, barklund approved these changes, later dismissed
This is really good, but just has a few issues.

- The current layer name should be extracted from the element type, but this work is already done in #11485, so feel free to merge that in once merged to main (@merapi will probably do that first thing Friday)
- The state of whether a layer is renamable should not exist in the story provider, but in some other location. Also, only one layer should ever be renamable.
- If a layer is renamed, the input should be focused (and the layer dialog should be open to do that). It should never be possible to have the rename input unfocused at all.

I have suggested fixes for all these inline below. I will tentatively approve pending the implementation of the above changes.

2022-05-13 02:01 UTC, barklund commented on packages/story-editor/src/components/panels/design/layer/layer.js
> +      : __('Renaming a layer.', 'web-stories')
This has to use the current "default" name that is returned by `LayerContent`. Currently this returns a component, but in my PR in #11429 it has been changed to a function, `getLayerText`, returning a simple string.

I have split the relevant part of the code into a new separate PR in #11485. Feel free to merge that one as soon as it is approved and then you can merge main in to update this part here.

2022-05-13 02:01 UTC, barklund commented on packages/story-editor/src/components/panels/design/layer/layer.js
> +              aria-label={__('Renaming a layer.', 'web-stories')}
I think the label should be `"Layer name"`, as that is what you're editing in the input.

2022-05-13 02:01 UTC, barklund commented on packages/story-editor/src/components/panels/design/layer/useLayerSelection.js
> +      if (evt.detail === 2 && !isLocked && !isBackground) {
The "detail === 2" part here definitely needs a comment (that it's a double click).

Alternatively, we have a `useDoubleClick` that we use elsewhere for these events.

2022-05-13 02:01 UTC, barklund commented on packages/story-editor/src/components/panels/design/layer/useLayerSelection.js
> +      if (evt.detail === 2 && !isLocked && !isBackground) {
Also, I think that locked layers can still be renamed. I don't see why not at least. Figma allows this, so I think we should just do that too.

2022-05-13 02:01 UTC, barklund commented on packages/story-editor/src/components/panels/design/layer/useLayerSelection.js
> +          properties: { isEditable: true },
This property doesn't belong here at all. The elements in the story are persisted to the database and changes add an entry into the history.

Saving this information directly on the element has a number of issues:

- It adds history entries
- It is stored to the database
- It causes needless re-renders
- It allows multiple layers to be renamed at the same time

See this for some issues, where I have multiple layers with an input field:
![Screen Shot 2022-05-12 at 21 26 40](https://user-images.githubusercontent.com/637548/168193160-13248e87-48b5-4f80-be5b-8a2fa2a82528.png)

I understand that this information needs to be available in both the canvas and the layer panel, so it has to be stored somewhere "high" in the component tree, but it should not be in the story provider directly. Perhaps it could be a new property in the canvas provider, with state`renamableLayer` and actions `setRenamableLayer` and `clearRenamableLayer` and then `null` means no layer is renamable, and some string means that the layer with the ID matching that string is renamable?

2022-05-13 02:01 UTC, barklund commented on packages/story-editor/src/components/panels/design/layer/layer.js
> +import { useRef, memo, useState } from '@googleforcreators/react';
This file is definitely getting too long. I also have additional edits in #114290, so if you have some extra time, it would be refactor this somewhat, alternatively just create a P2 follow-up ticket to refactor this component.

2022-05-13 02:01 UTC, barklund commented on packages/story-editor/src/app/rightClickMenu/items/layerName.js
> +          isEditable: oldElement.isLocked ? false : true,
This should again not go through the story provider, but some other provider. Also, why is the editable property set to the opposite of the locked property? And why not just use `!`?

2022-05-13 02:01 UTC, barklund commented on packages/story-editor/src/app/rightClickMenu/items/layerName.js
> +          isEditable: oldElement.isLocked ? false : true,
Oh yeah, and we need the property, wherever it ends up existing, to be called something like `renamable` or `changeLayerName` or something like that. `editable` is too broad a term, that we also use for other things, so it can get confusing (we have an edit-mode for elements, but it is completely unrelated to this property).

2022-05-13 02:01 UTC, barklund commented on packages/story-editor/src/app/rightClickMenu/items/layerName.js
> +          isEditable: oldElement.isLocked ? false : true,
Finally, the input field needs to be focused, and the layer panel needs to be opened if not already opened, when you right click to rename an element.

This should be done after the refactoring to a property on (e.g.) the canvas provider and then has to be done in two places:

1. In the footer layer button in `components/footer/layers`, the `isOpen` property should be set to true in an effect, if `renamableLayer` is non-null. That would force-open the dialog.
2. In the layer in `components/panels/design/layer/layer.js`, the input field should be focused in an effect, if `renamableLayer` is set to the specific layer. That would force-focus the input and it would work even if the layer panel was originally hidden.

2022-05-13 02:01 UTC, barklund commented on packages/story-editor/src/components/panels/design/layer/layer.js
> +import { useRef, memo, useState } from '@googleforcreators/react';
Come to think of it, the whole layer panel should even live inside `panels/design/` at all anymore. It's hardly a panel (doesn't really use any panel bits, except for an unpadded `PanelContent`, which could be removed), and it's definitely not related to the design panel at all.

So, follow-up ticket to refactor this component as well as move the whole layer dialog to a fresh location (probably as `components/layers` or something like that).

2022-05-13 02:01 UTC, barklund commented on packages/story-editor/src/components/panels/design/layer/layer.js
> +      : __('Renaming a layer.', 'web-stories')
Actually, the layer name, if provided, should be returned by all those `getLayerText` functions in all the different elements. It's not very DRY to go around adding this to 5 different functions.

Actually a better way to do it would be to create a single `getLayerName` function in the elements package, that would first look at `element.layerName` and if not set, use the layer name for the element type. This could also factor in the background layer name too. That's a much cleaner way to do it actually! I will amend #11485 to do that instead!

That would result in the custom layer name as entered by the user would also be used in the right-click select menu and as the aria-label for the element on the canvas (neither of which works currently).

See below, where the layer name is not used in the right-click menu:
![Screen Shot 2022-05-12 at 21 43 05](https://user-images.githubusercontent.com/637548/168194648-6f44af7e-b434-4753-9c94-bc83a239d9b4.png)

2022-05-13 02:01 UTC, barklund commented on packages/story-editor/src/components/panels/design/layer/layer.js
> +      : __('Renaming a layer.', 'web-stories')
I did this slight refactor in 57c7b283bc.

2022-05-13 09:42 UTC, mariana-k commented on packages/story-editor/src/components/panels/design/layer/layer.js
> +              aria-label={__('Renaming a layer.', 'web-stories')}
It's 'Renaming a layer.' in the Figma  design (the link to the design is in the ticket).

2022-05-13 11:06 UTC, merapi commented on packages/story-editor/src/components/panels/design/layer/useLayerSelection.js
> +          properties: { isEditable: true },
+1 for `renamableLayer` (id of the layer currently being renamed). Will look for a place for it.

2022-05-13 15:51 UTC, mariana-k commented on packages/story-editor/src/components/panels/design/layer/layer.js
> +      : __('Renaming a layer.', 'web-stories')
Done

2022-05-13 15:52 UTC, mariana-k commented on packages/story-editor/src/components/panels/design/layer/useLayerSelection.js
> +      if (evt.detail === 2 && !isLocked && !isBackground) {
Done

2022-05-13 20:23 UTC, merapi commented on packages/story-editor/src/components/panels/design/layer/layer.js
> +              aria-label={__('Renaming a layer.', 'web-stories')}
`Renaming a layer.` is just an example layer name in Figma, right? the input itself holds the layer name, so `Layer name` seems to be a good label for it.

2022-05-13 20:26 UTC, merapi commented on packages/story-editor/src/components/panels/design/layer/useLayerSelection.js
> +      if (evt.detail === 2 && !isLocked && !isBackground) {
@barklund WDYT about renaming the background layer? (`!isBackground` is now removed). Should we ask UX?

2022-05-17 03:20 UTC, mariana-k commented on packages/story-editor/src/components/panels/design/layer/useLayerSelection.js
> +          properties: { isEditable: true },
Moved code to the canvasProvider and fixed multiple renamable layers bug.

2022-05-17 16:27 UTC, marianakyrkosh commented on packages/story-editor/src/app/rightClickMenu/items/layerName.js
> +          isEditable: oldElement.isLocked ? false : true,
Done

2022-05-19 13:30 UTC, merapi requested changes
I'm reporting what I see in the current version:

1. After entering the edit mode (via double click) you cannot select a part of the text, instead it cancels the edit mode.

2. Go into edit mode, type something and cancel the edit mode (press Escape). The layer name is reverted to the old name - good, but when you enter the edit mode again you see the old (canceled) value.

3. ![image](https://user-images.githubusercontent.com/21036224/169303200-2281f56b-3ad5-4b46-98db-d31b0d7c5239.png)
This^ should look like it looked before (and in Figma). Those extra icons are unnecessary (I deleted my layer by accident when selecting text).

4. If the Background layer name cannot be changed then you shouldn't be able to enter the edit mode on that layer.

2022-05-26 13:25 UTC, barklund commented on packages/story-editor/src/components/panels/design/layer/layer.js
> +import { useRef, memo, useState } from '@googleforcreators/react';
* Added new issue #11576

2022-05-26 19:47 UTC, merapi approved these changes, later dismissed
This looks good now 👍🏻 

Nit: handling empty layer name.
Right now if you add layer `media/unsplash:gl8BgGhvVdg`, rename it to `layer1`, then rename it to empty string, it will become `media/unsplash:gl8BgGhvVdg`, but it should probably become `layer1`? Then if you enter the edit mode again - it will show an empty input (should always be the layer name visible before entering the edit mode?).

And a thing to consider: if we remove the `margin-left: 2px`, then the layer name will not shift when you enter the edit mode - it looks better IMO (even if it's 2px more over the icon).

2022-06-07 11:12 UTC, merapi approved these changes

2022-06-07 12:56 UTC, merged