Fix flip transform on drop targets and editing
GoogleForCreators/web-stories-wp pull request #1156
Opened 2020-04-10 12:32 UTC by wassgha

Closes #1111

### Changes
- Fixes an issue that caused drop targets and outlines to appear flipped when a transformation is applied
- Simplifies and fixes flipping on crop/edit

2020-04-10 16:17 UTC, dvoytenko approved these changes
Approved with one nit

2020-04-10 16:17 UTC, dvoytenko commented on assets/src/edit-story/masks/frame.js
> +    style.transform = style.transform
Please clone (not mutate) the prop.

2020-04-10 21:38 UTC, barklund commented
I found a really weird bug with a flipped mask and edit mode - I don't know if it's directly related to this one though or should be filed as a new one.

When entering edit mode for a flipped heart with an image inside, the image moved inside the mask. When I start dragging the image inside the mask, things start to get reaaaally funky!

![flipped-mask-bug](https://user-images.githubusercontent.com/637548/79024789-00d95800-7b52-11ea-8997-b554e230e693.gif)

2020-04-10 21:40 UTC, wassgha commented
Yeah I saw that, working on a fix in this PR

2020-04-13 13:23 UTC, miina requested changes
Please flip a video or image, enter edit mode and try panning - the panned image is not flipped.

`applyFlip` logic was there for a reason :)

2020-04-13 13:25 UTC, miina commented
@wassgha Just saw that Morten already mentioned the same bug, sorry for the repetition.

2020-07-09 13:41 UTC, swissspidy commented
@wassgha Hey Wassim, what's the status for this one?

2020-09-29 13:57 UTC, closed without merging