update frame with border
GoogleForCreators/web-stories-wp pull request #11628
Opened 2022-06-06 11:18 UTC by timarney

## Context

## Summary

## Relevant Technical Choices

## To-do

## User-facing changes

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Reviews

### Does this PR have a security-related impact?

### Does this PR change what data or activity we track or use?

### Does this PR have a legal-related impact?

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [ ] I have added a matching `Type: XYZ` label to the PR

---

Fixes #

2022-06-06 13:28 UTC, timarney commented
Tested with text as well.
<img width="302" alt="Screen Shot 2022-06-06 at 9 28 05 AM" src="https://user-images.githubusercontent.com/62242/172169984-7ce202fb-46ac-446c-b76e-da80164b1bf4.png">

2022-06-08 10:26 UTC, merapi commented
Looks promising, found just two things to fix:

1. In shapes, the bounding box is in the middle of the border (more visible for big borders, I use 40):
![image](https://user-images.githubusercontent.com/21036224/172593285-f05bc91d-f01e-4171-b55b-25bd2f864032.png)

2. Text resizing
Selected mode - ok:
![image](https://user-images.githubusercontent.com/21036224/172593437-d907f57a-334f-4b59-b677-3e2fd979817d.png)
Edit-mode - not sure if it's ok or not:
![image](https://user-images.githubusercontent.com/21036224/172593534-cba54b75-1035-4458-a6d5-dfbd52fc066c.png)
Started resizing (just 1px) - instant jump to big font:
![image](https://user-images.githubusercontent.com/21036224/172593773-dc1fb194-3fdc-432f-8108-5f6832cedb1f.png)

2022-06-08 12:39 UTC, barklund requested changes
This PR is missing implementing this one line from the original PR:

> Additionally, in discussion with George, we should include the border to the selection line as well.

However, you will find that this single line has a lot of consequences. It means that when you add border, the element in essence grows and that leads to many other changes. The size and position of the element as displayed and updated in the design panel updates. The element when dragged now snaps according to its outer border shape, not inner border shape. And other elements now snap to this one using its outer border shape, not inner. Especially this snapping stuff might be a bit tricky, which is why this is a pretty huge ticket to take on. And there are probably other consequences too, that I haven't considered.

2022-06-08 12:39 UTC, barklund commented on packages/story-editor/src/components/canvas/frameElement.js
> +    hasMask ? 'transparent' : theme.colors.border.selection};
Hmm, you seem to have your browser misconfigured. Prettier definitely wants that extra white-space here, so it should be reverted.

2022-06-09 15:10 UTC, timarney commented
https://github.com/GoogleForCreators/web-stories-wp/pull/11628#pullrequestreview-999648851

☝️ Noting comment above as it outlines what areas are impacted by any PR trying to fix this issue.


Adding a note just as I dig around.

Looking at this again from `main`

Depending on the type of shape looks like the border is applied either fully to the outside i.e. for rectangles vs other shapes it's in the middle ... 

<img width="500" alt="Screen Shot 2022-06-09 at 10 32 09 AM" src="https://user-images.githubusercontent.com/62242/172874026-9de8e6d2-188f-400c-8fc0-a1b510c1bbaf.png">



<img width="349" alt="Screen Shot 2022-06-09 at 11 08 30 AM" src="https://user-images.githubusercontent.com/62242/172880988-3f53680e-b727-4372-9a3e-6f82eecc69b0.png">

2022-06-14 11:40 UTC, timarney commented
Going to close this as I don't think this approach is going to work.

2022-06-14 11:40 UTC, closed without merging