Use dimensions not name of size.
GoogleForCreators/web-stories-wp pull request #12418
Opened 2022-10-03 15:42 UTC by spacedmonkey

## Context

## Summary

## Relevant Technical Choices

## To-do

## User-facing changes

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Reviews

### Does this PR have a security-related impact?

### Does this PR change what data or activity we track or use?

### Does this PR have a legal-related impact?

Another solution to #12354. If you pass an array of dimensions instead of passing size name it bypasses the content width check. [See](https://github.com/WordPress/wordpress-develop/blob/5eddc8f18c97d2eb909d0f70f4e20732398a7bda/src/wp-includes/media.php#L69-L71)

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #12354

2022-10-05 07:03 UTC, swissspidy commented
Does it work?

As discussed, would be nice to have some sorts of tests verifying that this actually solves the reported bug. With this approach here it should be doable to that with PHP tests alone, no E2E tests needed (though that would be the last resort).

Alternatively, if we can't have tests, at the very least we should add comments explaining why we do it that way.

2022-10-05 14:15 UTC, spacedmonkey commented
@swissspidy Unit tests added. Closing other PR in favour of this.

2022-10-05 18:20 UTC, timarney commented on tests/phpunit/integration/tests/REST_API/Stories_Controller.php
> +				'height'     => $attachment_src[2],
Nit: can we flip these so it's width before height 

width [1]
width [2]

Little better readability IMO

2022-10-05 18:22 UTC, timarney commented on tests/phpunit/integration/tests/REST_API/Stories_Controller.php
> +				'height'     => $attachment_src[2],
Same Nit as above 

```
'width' => $attachment_src[1],
'height' => $attachment_src[2],
```

Would be more readable

2022-10-05 18:23 UTC, timarney commented on tests/phpunit/integration/tests/REST_API/Stories_Controller.php
> +				'height'     => $attachment_src[2],
Same again here:

```
'width' => $attachment_src[1],
'height' => $attachment_src[2],
```

2022-10-12 23:43 UTC, swissspidy commented
The tests don't work, as in, they demonstrate the bugfix. If I undo the changes to `includes/REST_API/Stories_Controller.php` and `includes/Model/Story.php` they still pass.

----

Note that for the QA instructions you can reuse the reproduction steps from the issue.

2022-10-13 10:44 UTC, spacedmonkey commented
> The tests don't work, as in, they demonstrate the bugfix. If I undo the changes to includes/REST_API/Stories_Controller.php and includes/Model/Story.php they still pass.

The fix does work, I just used the wrong test data. I have updated the fixture data and tests pass and you can see them pass.

2022-10-13 15:37 UTC, swissspidy commented
When I undo the changes to `includes/REST_API/Stories_Controller.php` I expect the `Stories_Controller` tests to fail, but they don't.

2022-10-13 15:38 UTC, swissspidy commented
Also, running the tests creates a bunch of untracked files in the tests directory:

<img width="591" alt="Screenshot 2022-10-13 at 08 38 11" src="https://user-images.githubusercontent.com/841956/195642111-84ec9f05-1b64-4641-b414-5f90e3bd481f.png">

2022-10-17 07:22 UTC, swissspidy requested changes
A couple of adjustments needed, as per my recent comments

2022-10-17 07:23 UTC, swissspidy commented
QA instructions would be needed too here

2022-10-17 10:26 UTC, spacedmonkey commented
> Also, running the tests creates a bunch of untracked files in the tests directory:
> 
> <img alt="Screenshot 2022-10-13 at 08 38 11" width="591" src="https://user-images.githubusercontent.com/841956/195642111-84ec9f05-1b64-4641-b414-5f90e3bd481f.png">

I added delete attachment calls to all places where image sizes are generated.

2022-10-19 10:35 UTC, swissspidy commented
> When I undo the changes to `includes/REST_API/Stories_Controller.php` I expect the `Stories_Controller` tests to fail, but they don't.

This still needs to be addressed AFAICT. After that this should be ready.

2022-10-19 10:40 UTC, spacedmonkey commented
> This still needs to be addressed AFAICT. After that this should be ready.

I believe I fixed these issues with new test data.

2022-10-19 10:44 UTC, swissspidy commented
Just verified that it's still an issue.

2022-10-19 11:23 UTC, spacedmonkey commented
> Just verified that it's still an issue.
> 
> [3be82da](https://github.com/GoogleForCreators/web-stories-wp/commit/3be82daae767ee8bfb53c4776a33942d4435f4b0) was the only change since I flagged this.

Fix the unit test here. https://github.com/GoogleForCreators/web-stories-wp/pull/12418/commits/21de72a614073c7fd5a4c82ee3406c7b43602931

2022-10-19 11:32 UTC, swissspidy commented
Excellent! 🎉

2022-10-19 11:33 UTC, swissspidy approved these changes

2022-10-19 18:05 UTC, kkalarickal commented
Reproduced this problem (thanks to @LuckynaSan and @spacedmonkey for your help) by following these steps:

1. Switch to an older theme (I tried Twenty-Twenty, Twenty-Nineteen, Twenty-8teen, Twenty-Seventeen)
2. Create a sample web story and save to draft
3. Hit publish and update the poster image by selecting a larger image and cropping it
4. Exit from editor and reopen the same published story -- Now you will see the incorrect checklist error saying poster image size is not up to expected 640x853. This is in spite of the image being cropped properly.

Verified the fix by loading the `12418 branch` in the same wp environment with the older theme and repeating the steps above to confirm that the checklist does NOT report a non-existent problem.

2022-10-19 19:23 UTC, merged