Media Recording: Improve settings dialog
GoogleForCreators/web-stories-wp pull request #12548
Opened 2022-10-26 09:54 UTC by timarney

## Context

Add visual labels to the video settings dropdowns

## Summary

## Relevant Technical Choices

## To-do

## User-facing changes

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Reviews

### Does this PR have a security-related impact?

### Does this PR change what data or activity we track or use?

### Does this PR have a legal-related impact?

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [ ] I have added a matching `Type: XYZ` label to the PR

---

Fixes #12312

2022-10-27 06:25 UTC, swissspidy commented on packages/story-editor/src/components/mediaRecording/settingsModal.js
> +            {__('Video Input', 'web-stories')}
```suggestion
            {__('Camera', 'web-stories')}
```

2022-10-27 06:26 UTC, swissspidy commented on packages/story-editor/src/components/mediaRecording/settingsModal.js
> +            {__('Audio Input', 'web-stories')}
```suggestion
            {__('Microphone', 'web-stories')}
```

2022-10-27 06:26 UTC, swissspidy commented
Can you add before/after screenshots to the PR description under "user-facing changes" please? Makes it easier to see the difference.

2022-10-27 10:28 UTC, merapi approved these changes

2022-10-27 12:14 UTC, swissspidy requested changes, later dismissed
This should be a semantic `<label>` element that is connected to the input via a `for`/`htmlFor` attribute.

With our `Text` component from the design system you can achieve this by doing `<Label as="label">`.

2022-10-27 21:54 UTC, spacedmonkey commented
+1 for labels. Labels should be click and that should focus on the dropdown.

2022-10-27 23:30 UTC, timarney commented
Updated to use Label `as`
<img width="1207" alt="Screen Shot 2022-10-27 at 7 29 44 PM" src="https://user-images.githubusercontent.com/62242/198416522-ab371ddf-bb19-4472-af62-65f13e6f7bd8.png">

2022-10-28 09:52 UTC, spacedmonkey approved these changes

2022-10-31 07:41 UTC, swissspidy approved these changes

2022-10-31 07:45 UTC, merged