bump at least version
GoogleForCreators/web-stories-wp pull request #12613
Opened 2022-11-03 08:53 UTC by timarney

## Context

## Summary

## Relevant Technical Choices

## To-do

## User-facing changes

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Reviews

### Does this PR have a security-related impact?

### Does this PR change what data or activity we track or use?

### Does this PR have a legal-related impact?

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [ ] I have added a matching `Type: XYZ` label to the PR

---

Fixes #12582

2022-11-03 10:58 UTC, swissspidy commented
Marking as **blocked** just so we don't merge this before the next release, which is slated for next week, since this change is intended to be in the release after it.

2022-11-04 10:06 UTC, swissspidy commented
Let's also update `minimum_supported_wp_version` in `phpcs.xml.dist`

2022-11-04 15:52 UTC, spacedmonkey requested changes, later dismissed
To compare https://github.com/GoogleForCreators/web-stories-wp/commit/fd13b45857fa94db27adf7e03bc8a26e2251665b. The only change that is missing is `minimum_supported_wp_version` in phpcs.xml.dist.

2022-11-09 12:34 UTC, swissspidy approved these changes

2022-11-09 12:38 UTC, merged