Add result count per all/draft/active story type
GoogleForCreators/web-stories-wp pull request #1312
Opened 2020-04-23 04:58 UTC by cvolzke4

When searching and filtering results on the dashboard, add the number of results per status (e.g. 10 totals, 5 drafts, 5 published).

TODO in follow-up changes:
- Split myStories/index.js into multiple files, to make testing easier.
- Write a test.
- "show the total number of results" - figure out what this means.

2020-04-23 15:47 UTC, BrittanyIRL requested changes
Hi @cvolzke4  - welcome to the team! 

I'm so glad you're jumping in to start tackling smaller tasks and that this happened is a sign that we all need to do better at marking things blocked for transparency - especially with all the timezones we span now. 

Adding counts by story type to the filters on the my stories view is actually a little more complicated than this because the API is paginated. So we have this story:  https://github.com/google/web-stories-wp/issues/1120

which I think you referenced, but the API currently doesn't give us the ability to get the total by story status without also loading all of the stories. So 1120 is for getting a new header response akin to the totalPages and total (which is the total of all the stories for that query regardless of page) to get the count by status also returned to us so we can have reliable numbers without also loading all of the pages of stories which is unnecessary for our purposes. 

So the hope here is that once the API is updated with those headers we can store them with the rest of our stories state and access it through context, eliminating the need to do this filtering at all on the view. 

Does that make sense? 

As for your todos - great call out for the size of the myStories view - we've been iterating pretty fast on this view, using it as kind of the test-run for then implementing the other pages. We're moving parts out as we go and writing tests for the smaller components seen in the view, albeit we can definitely up our coverage! I also have wanted to make storybook components for the shared view components found in dashboard/app/views/shared.  So I do appreciate you pointing these out, that as a person entering the team this is an added hurdle that isn't necessary! I'll try to work on this readability towards the end of the week to allow you and your team an easier ramp up. 

Please let me know if you have questions or want to talk through any of this! I'm in MST but if necessary I'd be happy to get back online in my evening to overlap with your daytime just to get up to speed. Thanks again for jumping in to this so fast, we're excited about this project!

2020-04-28 04:24 UTC, cvolzke4 commented
> Hi @cvolzke4 - welcome to the team!

Thanks Brittany! :)

I missed this context in the ticket, I thought it was only relevant to the template.

Would a sensible approach be to send 3 queries and read the 'X-WP-Total' response header from each:
- status=all, per_page=1   (or 0)
- status=draft, per_page=1
- status=live, per_page=1

Or is the plan for us to write a new API on the Wordpress side in PHP?

2020-04-28 16:52 UTC, BrittanyIRL commented
> > Hi @cvolzke4 - welcome to the team!
> 
> Thanks Brittany! :)
> 
> I missed this context in the ticket, I thought it was only relevant to the template.
> 
> Would a sensible approach be to send 3 queries and read the 'X-WP-Total' response header from each:
> 
> * status=all, per_page=1   (or 0)
> * status=draft, per_page=1
> * status=live, per_page=1
> 
> Or is the plan for us to write a new API on the Wordpress side in PHP?

No worries! 
So I belive the plan is to add new headers to the existing API, that's what the ticket #1120 is for for Pascal and Miina to address the changes in PHP

2020-05-14 12:17 UTC, swissspidy commented
Heya @cvolzke4!

#1761 has just been merged, which adds a new `X-WP-TotalByStatus` HTTP response header. This should unblock this PR.

2020-05-14 14:46 UTC, closed without merging