Image alt tag accessibility fix
GoogleForCreators/web-stories-wp pull request #1341
Opened 2020-04-27 06:25 UTC by diegovar

2020-04-27 09:22 UTC, spacedmonkey commented
Seems like this bug is #1128

Any chance you could also fix the other fields I reference in the ticket?

2020-04-27 10:06 UTC, spacedmonkey commented on assets/src/edit-story/components/panels/videoAccessibility.js
> +  const _defaultForUndefined = (s, d) => (s === undefined ? d : s);
Why is this needed? Doesn't `getCommonValue` already have a param default value? Why can't we use that?

2020-04-27 22:59 UTC, dvoytenko requested changes

2020-04-27 22:59 UTC, dvoytenko commented on assets/src/edit-story/components/panels/imageAccessibility.js
> +  const altValue = getCommonValue(selectedElements, 'alt');
Ditto: please check the 3rd arg.

2020-04-28 01:17 UTC, diegovar commented
Closing as I'll move the changes to https://github.com/google/web-stories-wp/pull/1340

2020-04-28 01:17 UTC, closed without merging