[Task] Smoother more deterministic squish
GoogleForCreators/web-stories-wp pull request #1554
Opened 2020-05-05 16:22 UTC by littlemilkstudio

## Summary
Looked at subbing out `IntersectionObserver` with a throttled scroll event because `IntersectionObserver` wasn't firing reliably for every threshold. This was causing small noticeable ticks & sometimes ending at arbitrary values like `0.956` instead of 1.

After doing a performance audit on both, it seemed neither was a current bottleneck and performed about the same:
- *no throttling* - 60fps
- *4x slowdown* - 40fps
- *6x slowdown* - 30fps

I think if we want to make this more performant, we should get clever with the properties we're interpolating on `squish` events and make them more compositor friendly. currently animating `font-size` & `margin-top`. Could finagle these into `transform` if needed

## Relevant Technical Choices
- Changed `squish` event source to be a scroll event vs an intersection observer with multiple thresholds
- Added a `throttleToAnimationFrame` to wrap the scroll handler
- Added tests for `throttleToAnimationFrame` which I created a mock `rafScheduler` for if anyone needs to use this,

Fixes #
- ending on non-deterministic progress values (close to 1, but not 1)
- smoother scroll reactiveness. (updates squish from exact scroll on each animation frame unlike the intersection observer which inconsistently chose thresholds to fire)

2020-05-05 17:10 UTC, carloskelly13 approved these changes
Tested this and it's smooth in Safari, Chrome and Firefox.

No interaction in Safari was over 15ms and in Firefox we showed an average of 58 fps

<img width="127" alt="Screen Shot 2020-05-05 at 12 09 51 PM" src="https://user-images.githubusercontent.com/1738349/81094610-63abde00-8ec9-11ea-8ef5-7dd653f68b8f.png">

2020-05-05 17:10 UTC, carloskelly13 requested changes

2020-05-05 17:10 UTC, carlos-kelly commented on assets/src/dashboard/utils/throttleToAnimationFrame.js
> + */
We can drop this comment as there are no external reps

2020-05-06 15:35 UTC, BrittanyIRL approved these changes
This works great! I really like the tests you added - seeing unit tests for animation is really cool. And that making this more performant means less lines of code/complexity! Awesome!

2020-05-06 15:35 UTC, BrittanyIRL commented on assets/src/dashboard/components/layout/provider.js
> +    const handleScroll = throttleToAnimationFrame((e) => {
nit: if `target` is the only thing getting used out of `e` might as well destructure it `(({target}) => `

2020-05-06 20:47 UTC, carloskelly13 approved these changes
This runs really well. The one minor alignment issue I see is the baselines don't match up. We might need to either `cssLerp` a 2px top margin or just make the min font bigger.

I am getting a consistent 58-60 fps just scrolling up and down.

<img width="797" alt="Screen Shot 2020-05-06 at 3 45 56 PM" src="https://user-images.githubusercontent.com/1738349/81226629-c4621600-8fb0-11ea-8c17-26922f1194f7.png">

2020-05-06 20:59 UTC, merged