Prototype numeric input scrubber
GoogleForCreators/web-stories-wp pull request #1775
Opened 2020-05-14 08:17 UTC by wassgha

![Draggable numeric input](https://user-images.githubusercontent.com/591655/81910287-9b2d2100-9580-11ea-8af9-3fb25fccfc7a.gif)

## Summary

Prototype requested by @samitron7 to demo a dragging gesture for changing numeric values. Differentiates between a click (to manually edit the numeric input by keyboard) and a drag.

## To-do
- [ ] Clean up code (use a mapping between pixels and numeric values)
- [ ] Add min/max bounds
- [ ] Handle mouse movement outside of input container
- [ ] Fix race condition between updating value and submitting the form
- [ ] Touchscreen compatibility
- [ ] Restore ability to select text while focused

Closes #1053

2020-05-14 14:33 UTC, samitron7 commented
@wassgha thanks so much for getting this in and it's 1AM in the morning! Anyway I can play around with this myself?

2020-05-14 14:39 UTC, swissspidy commented
@samitron7 You can use [the QA environment](https://stories-qa-wordpress-amp.pantheonsite.io/) I sent an email about the other day.

Check https://github.com/google/web-stories-wp/blob/master/docs/testing-environments.md for access and https://github.com/google/web-stories-wp/blob/master/docs/testing-qa.md#web-stories-tester-plugin for how to test  this particular change.

Basically, you log in on https://stories-qa-wordpress-amp.pantheonsite.io/ with your username, then select `#1775 - Prototype...` from the `Using Web Stories` UI in the upper right corner and then click "Activate Selection". It might take a few moments to reflect the changes. After that, head to the editor.

2020-05-26 19:47 UTC, dvoytenko requested changes
I think this looks pretty good.

2020-05-26 19:47 UTC, dvoytenko commented on assets/src/edit-story/components/form/numeric.js
> +    onMouseMove: useCallback(
Can we do `onPointer*` events instead?

2020-05-26 19:47 UTC, dvoytenko commented on assets/src/edit-story/components/form/numeric.js
> +    onMouseDown: (e) => {
IMHO it'd be nicer to move these methods up with `mouseUpCallback`.

2020-05-26 19:47 UTC, dvoytenko commented on assets/src/edit-story/components/form/numeric.js
> +      e.target.ownerDocument.addEventListener(
Can we use pointer capture for this instead?

2020-09-22 20:04 UTC, closed without merging