Dashboard: Adds Tooltips. Borders around Preview Cards.
GoogleForCreators/web-stories-wp pull request #1800
Opened 2020-05-15 01:53 UTC by carlos-kelly

Adds tooltip components and overlay to view toggle.

Secondarily adds borders around the preview cards and prevents off-canvas elements from showing up.

<img width="242" alt="Screen Shot 2020-05-14 at 5 32 12 PM" src="https://user-images.githubusercontent.com/1738349/82002924-b9e4f380-9624-11ea-953f-25e085f9ef91.png">
<img width="387" alt="Screen Shot 2020-05-14 at 8 31 06 PM" src="https://user-images.githubusercontent.com/1738349/82002925-b9e4f380-9624-11ea-9b24-144f82cc3d52.png">

## Relevant Technical Choices

- Uses mouse events to control visibility of the tooltip since they are more predictable and controllable  

Fixes #1489

2020-05-15 19:21 UTC, mariano-formidable requested changes
Only some nits to think about, but mostly, can you add some tooltip stories (long and short text), it'd be great to easily see examples of it running without having to figure out where they're tagged on the site.  Other than that, great work!

2020-05-15 19:21 UTC, mariano-formidable commented on assets/src/dashboard/components/tooltip/index.js
> +  label: propTypes.string.isRequired,
Nice clean tooltip implementation.  I understand `label` being a string right now since that's all we need, but do you think it might be more flexible if we could pass in `tooltipContent` as a react node or something, and then we can have anything appear in the tooltip?  It's an easy enough refactor in the future so no need to do now if this will cover our uses cases at the moment.

2020-05-15 19:21 UTC, mariano-formidable commented on assets/src/dashboard/components/cardGridItem/cardPreview.js
>    border-radius: 8px;
I know this isn't technically part of your PR but since you're adding box-shadow, maybe you can adjust the border radious for the story cards too.  It looks like the new designs have the border radius less intense:

Ours at 8px:
![image](https://user-images.githubusercontent.com/40646372/82088271-497eb680-96a6-11ea-8092-a000c7bb2b69.png)

New design at... probably 4px?
![image](https://user-images.githubusercontent.com/40646372/82088308-5d2a1d00-96a6-11ea-90e3-6ee9a1270f4e.png)

2020-05-15 19:37 UTC, BrittanyIRL reviewed
Works great! Borders on the grid items help alot. 
(+1 for storybook adds)

Only thing I see is - something is happening on Safari that's making the text wrap despite ample space for the tooltip to be one line? 
![Screen Shot 2020-05-15 at 12 35 50 PM](https://user-images.githubusercontent.com/10720454/82089614-c9a61b80-96a8-11ea-8b6a-3fa1d91c1642.png)

2020-05-15 19:37 UTC, BrittanyIRL commented on assets/src/dashboard/components/tooltip/index.js
> +  transition: opacity linear 200ms;
nit: transition shorthand should be `name | duration | timing function` 
<img width="334" alt="Screen Shot 2020-05-15 at 12 31 28 PM" src="https://user-images.githubusercontent.com/10720454/82089268-2b19ba80-96a8-11ea-9683-2deec037d261.png">

2020-05-15 19:43 UTC, maxyinger approved these changes
Looks great!

2020-05-15 19:43 UTC, maxyinger commented on assets/src/dashboard/components/tooltip/index.js
> +  width: max-content;
very cool. never used `max-content` before. TIL

2020-05-15 19:43 UTC, maxyinger commented on assets/src/dashboard/components/viewStyleBar.js
> +  const toggleRef = useRef();
don't think I'm following the use for this. I see it getting attached to `<Container ref={toggleRef}>` but don't see `toggleRef` referenced anywhere else. What's it being used for?

2020-05-15 19:43 UTC, maxyinger commented on assets/src/dashboard/theme.js
> +    shadow: '1px 1px 5px hsla(0, 0%, 0%, 0.15)',
small nit. do we want either `hsla(0%, 0%, 0%, 0.15)` or `hsla(0, 0, 0, 0.15)`? don't think it'll break anything but just noticed.

2020-05-15 19:43 UTC, maxyinger commented on assets/src/dashboard/components/tooltip/index.js
> +  ['data-testid']: 'tooltip-container',
is there a benefit of declaring the testid here vs in the jsx? fine either way, just asking for learning purposes

2020-05-15 19:45 UTC, littlemilkstudio commented
> Works great! Borders on the grid items help alot.
> (+1 for storybook adds)
> 
> Only thing I see is - something is happening on Safari that's making the text wrap despite ample space for the tooltip to be one line?
> ![Screen Shot 2020-05-15 at 12 35 50 PM](https://user-images.githubusercontent.com/10720454/82089614-c9a61b80-96a8-11ea-8b6a-3fa1d91c1642.png)

weird. seems to be supported in safari. guess it's just how they interpret some styles??  🤷 https://developer.mozilla.org/en-US/docs/Web/CSS/width#max-content

2020-05-15 22:07 UTC, carlos-kelly commented on assets/src/dashboard/components/tooltip/index.js
> +  ['data-testid']: 'tooltip-container',
I think it's personal preference really.

2020-05-15 22:23 UTC, carlos-kelly commented
@mariano-formidable Good call on the storybook. I added the ability to left, center, or right position the tooltip and the config options are in the story.

<img width="229" alt="Screen Shot 2020-05-15 at 4 47 05 PM" src="https://user-images.githubusercontent.com/1738349/82100938-b5761480-96d0-11ea-8a38-ae7dc286e1a5.png">
<img width="229" alt="Screen Shot 2020-05-15 at 4 47 10 PM" src="https://user-images.githubusercontent.com/1738349/82100940-b60eab00-96d0-11ea-8f11-4f45b1292b72.png">
<img width="216" alt="Screen Shot 2020-05-15 at 4 47 14 PM" src="https://user-images.githubusercontent.com/1738349/82100941-b60eab00-96d0-11ea-894c-c7fe6135a881.png">

2020-05-15 22:34 UTC, BrittanyIRL approved these changes
LGTM! consistent tooltips across browsers.

2020-05-15 23:15 UTC, mariano-formidable requested changes

2020-05-15 23:15 UTC, mariano-formidable commented on assets/src/dashboard/components/cardGridItem/cardPreview.js
> +  border-radius: 4px;
Noice!  But I think the `EditControls` component right below this one (on line 54) needs to be 4px too... 😱

2020-05-15 23:15 UTC, mariano-formidable commented on assets/src/dashboard/components/cardGridItem/cardPreview.js
> +  border-radius: 4px;
Screenshot to show how it's looking (on hover), notice the small gap between the gray and the card:
![image](https://user-images.githubusercontent.com/40646372/82103236-1f89bc00-96c7-11ea-98a4-8337ec932ba5.png)

2020-05-18 13:08 UTC, carlos-kelly commented
@mariano-formidable Good call on the radius. 

I made `theme.storyPreview.borderRadius` a theme var so we can now change it in one place and then it hits the 3 usage spots.

<img width="299" alt="Screen Shot 2020-05-18 at 8 06 22 AM" src="https://user-images.githubusercontent.com/1738349/82216362-7ae1c700-98de-11ea-88e1-89875105c641.png">

2020-05-18 15:28 UTC, mariano-formidable reviewed
Looks good to me!

2020-05-18 15:29 UTC, mariano-formidable approved these changes

2020-05-18 16:03 UTC, merged