Drop target prioritization
GoogleForCreators/web-stories-wp pull request #1994
Opened 2020-05-26 16:31 UTC by wassgha

Closes #943

Fixes drop target targeting the lower z-index elements instead of the highest element on the stack.

2020-05-26 19:42 UTC, dvoytenko requested changes

2020-05-26 19:42 UTC, dvoytenko commented on assets/src/edit-story/components/dropTargets/provider.js
> +      const sortedDropTargetIds = (currentPage?.elements || [])
It looks like `getDropTargetFromCursor` is called a lot? Would it be better to do:

```
const sortedDropTargetIds = useMemo(() => ..., [dropTargets, currentPage?.element]);

const getDropTargetsFromCursor = useCallback( () => ..., [sortedDropTargetIds])
```
?

2020-05-27 19:49 UTC, barklund reviewed
This works excellently!

Could we add a karma test for this? It's a fairly complex setup, but should be doable. Maybe also some base tests about drop targets in general, when you're at it?

2020-06-16 12:59 UTC, swissspidy commented
FYI @merapi your call to ping the bot ^

2020-06-16 15:26 UTC, wassgha commented
@googlebot I consent.

2020-06-16 15:46 UTC, merapi commented
@googlebot I consent.

2020-06-16 16:02 UTC, merapi commented on assets/src/edit-story/components/canvas/displayLayer.js
> +    <Layer data-testid="DisplayLayer" pointerEvents="none">
Until https://github.com/google/web-stories-wp/pull/2386 is merged.

2020-06-16 16:04 UTC, merapi approved these changes
Works as expected.

2020-06-16 22:26 UTC, dvoytenko approved these changes

2020-06-16 22:28 UTC, merged

2020-06-18 01:43 UTC, barklund commented
Did this pass through QA?