Feature | WAAPI Pause & setCurrentTime Aggregate methods
GoogleForCreators/web-stories-wp pull request #2004
Opened 2020-05-26 19:21 UTC by littlemilkstudio

## Summary
- Converts `playWAAPIAnimations` method to be `WAAPIAnimationMethods.play`.
- Adds `WAAPIAnimationMethods.pause`
- Adds `WAAPIAnimationMethods.setCurrentTime`
- Updates tests and stories to highlight new methods.

## Relevant Technical Choices
Only way to reset the animation while it's in the middle of playing is to set the current time of the animation back to 0, but just realized  `currentTime` isn't supported by safari 😢. as well as `pause`.
https://developer.mozilla.org/en-US/docs/Web/API/Animation/currentTime
https://developer.mozilla.org/en-US/docs/Web/API/Animation/pause

Does anyone else see a way to do this with existing methods in web animations api? 
Should we design this to be an enhancement?
is it worth investing time in using a different animation library?

## To-do
- utilize these methods in the preview grid to abort animations mid-way through.

## User-facing changes
- none

## Testing Instructions
- Added test coverage in unit tests, so make sure unit tests pass for this section
- Go to storybook `dashboard > Story Animation > default` and use the pause and reset buttons.

---

https://app.zenhub.com/workspaces/web-stories-5e94d3aced449034e1e9b226/issues/google/web-stories-wp/1886

2020-05-26 22:52 UTC, mariano-formidable requested changes
I'm getting this error in Storybook (Animations -> BlinkOn -> Default.  Does it work for you?
![image](https://user-images.githubusercontent.com/40646372/82957762-af9df000-9f68-11ea-8d1f-1dbd18839ea5.png)

Also it looks like one of the javascript tests is failing 😱

2020-05-27 22:28 UTC, littlemilkstudio commented
> I'm getting this error in Storybook (Animations -> BlinkOn -> Default. Does it work for you?
> ![image](https://user-images.githubusercontent.com/40646372/82957762-af9df000-9f68-11ea-8d1f-1dbd18839ea5.png)
> 
> Also it looks like one of the javascript tests is failing 😱

Yea just finished fixing all this today. All this should hopefully be addressed with the latest changes. Definitely check both `Animations -> Blink On` & `Dashboard -> StoryAnimation` for both defaults and amp on safari.

2020-05-28 16:34 UTC, mariano-formidable requested changes
Overall, it looks and works great (even in Safari).  I noticed the same reset issue that Brittany noticed (there may not be anything we can do about it now, so I don't see it as a blocking issue if that's the best the API can handle for now).  

I only have some nits for you to consider.

Oh and a StoryAnimation.Provider test is failing:
![image](https://user-images.githubusercontent.com/40646372/83168442-5946c380-a0c6-11ea-9d72-ff0bea85851f.png)

2020-05-28 16:34 UTC, mariano-formidable commented on assets/src/dashboard/animations/parts/bounce/index.js
> +];
Noice! 🎉

2020-05-28 16:34 UTC, mariano-formidable commented on assets/src/dashboard/components/storyAnimation/test/provider.js
> +      // expect(getAnimationParts('not used target')).toHaveLength(0);
Are these commented out assertions no longer needed?  Can they be removed?

2020-05-28 16:34 UTC, mariano-formidable commented on assets/src/dashboard/components/storyAnimation/provider.js
> +      setCurrentTime: (time) =>
Would it make sense to make a `reset` action that internally calls `setCurrentTime(0)` and `pause()`?  This way it'll be clear that we support `reset` (and how we support it), and should there ever come a time when resetting is natively supported by the WAAPI, we'd just have to update our `reset` action and boom, all reset calls around the codebase would be updated.

2020-05-28 19:29 UTC, littlemilkstudio commented
> Oh and a StoryAnimation.Provider test is failing:

Ahh yeaup. fixing now. Also think I have a solution for the problem brittany mentioned

2020-05-28 22:44 UTC, BrittanyIRL reviewed
play, pause and reset  are all working in firefox, chrome, and safari on default animations in storybook and unit tests run fine locally. 

One weird thing I noticed, if you hit 'pause' first instead of 'play' the animation goes to a different view that i can't figure out the pattern for. Some of them disappear and others show just one element? 
![initialpause disappears](https://user-images.githubusercontent.com/10720454/83201289-0686ff00-a0fa-11ea-94e7-7e0c06f34207.gif)
![fade pause first](https://user-images.githubusercontent.com/10720454/83201391-3afabb00-a0fa-11ea-9b1e-eda48f61675e.gif)

2020-05-28 23:59 UTC, mariano-formidable approved these changes
Looks good to me!

2020-05-29 16:04 UTC, littlemilkstudio commented
@BrittanyIRL 
> One weird thing I noticed, if you hit 'pause' first instead of 'play' the animation goes to a different view that i can't figure out the pattern for. Some of them disappear and others show just one element?

Yea so it has to do with animation fills that are dictated by the animation part. with the one with the two squares it's because both are animated at the same time the red being from `0 -> 1` and the orange being from `1 -> 0` so when you hit pause it applies the initial frame of the animation which for the orange & the red square is `opacity: 0` & `opacity: 1` for the boxes bouncing in, it's `scale: 0` for all of them.

Needless to say, that's the current expected behavior. 

Inside the story cards we could apply the first or last frame of the animation on mount if we want to, but I wanna wait till we get to a hands on implementation till we make those decisions.

Also worth noting that only the `play` & `reset` methods will probably be used inside the story cards. `pause` is just a method that `reset` uses internally that we exposed for storybook

2020-05-29 16:06 UTC, merged