Adapt popup height to contents
GoogleForCreators/web-stories-wp pull request #2306
Opened 2020-06-08 15:12 UTC by wassgha

## Summary

Makes the popup component dynamically adapt to height changes of its content, thereby preventing scrollable overflow (especially visible on the calendar element which switching views, see https://github.com/google/web-stories-wp/pull/1743#discussion_r427682509). 

## Relevant Technical Choices

## To-do

- [ ] Trigger the height change automatically without need for a scroll event

## User-facing changes

- Link popups are now fixed (no longer showing an unnecessary scroll bar)
- Calendar will now be fully visible without need for scrolling

## Testing Instructions

- See https://github.com/google/web-stories-wp/pull/1743#discussion_r427682509

---

Fixes #1931 , see context on https://github.com/google/web-stories-wp/pull/1743#discussion_r427682509
Part of #1082

2020-06-08 15:13 UTC, wassgha commented on assets/src/edit-story/components/inspector/document/publish/publishTime.js
> +              propagateDimensionChange();
@miina this is currently not triggered when switching between views, which makes it require a scroll before the change is in effect. I tried using `onViewChange` from the `react-calendar` but that did not work either, any ideas?

2020-06-10 15:58 UTC, wassgha commented
@miina any input on this please?

2020-06-10 18:01 UTC, miina commented
@googlebot I consent.

2020-06-10 18:01 UTC, miina commented
@wassgha: 
`onViewChange` seems to work when testing locally -- added a commit with that (de1b502) -- could you confirm that it's not working for you?

2020-06-10 18:04 UTC, miina commented on assets/src/edit-story/components/inspector/document/publish/publishTime.js
> +
(Whoops, left an empty line in, didn't run the commit through the linter, sorry)

2020-06-10 20:21 UTC, dvoytenko requested changes

2020-06-10 20:21 UTC, dvoytenko commented on assets/src/edit-story/components/form/dateTime/datePicker.js
> +  onViewChange: PropTypes.func.isRequired,
IMHO this should be an optional arg

2020-06-10 20:21 UTC, dvoytenko commented on assets/src/edit-story/components/popup/index.js
> +          {typeof children === 'function'
This is pretty complicated. Can we just use a context here? Or even simply bubble a custom event and handle it here? Also, would a container with the `ResizeObserver` work for this?

2020-06-16 15:26 UTC, wassgha commented
Ready!

2020-06-16 15:28 UTC, miina commented on assets/src/edit-story/components/form/dateTime/datePicker.js
> +  onViewChange: PropTypes.func.isRequired,
@wassgha This still seems to be required though, did you leave it in purposefully?

2020-06-16 15:31 UTC, wassgha commented on assets/src/edit-story/components/form/dateTime/datePicker.js
> +  onViewChange: PropTypes.func.isRequired,
No, sorry, it got reverted :)

2020-06-16 15:35 UTC, miina approved these changes
LGTM!

2020-06-16 22:19 UTC, dvoytenko approved these changes

2020-06-16 22:25 UTC, merged