Fix paste upload
GoogleForCreators/web-stories-wp pull request #241
Opened 2020-02-06 14:19 UTC by spacedmonkey

Paste uploading was added by mistake in #195 . It doesn't work as is, let's fix it.

2020-02-06 17:05 UTC, miina approved these changes

2020-02-06 19:09 UTC, gitjoao approved these changes

2020-02-06 19:31 UTC, dvoytenko requested changes

2020-02-06 19:31 UTC, dvoytenko commented on assets/src/edit-story/components/canvas/useCanvasSelectionCopyPaste.js
> +				// Can't use deconstructor here.
Why not?

2020-02-10 14:03 UTC, spacedmonkey commented
Fixed in #210

2020-02-10 14:03 UTC, closed without merging