Ensure raw story title is used for prefilling post title
GoogleForCreators/web-stories-wp pull request #2906
Opened 2020-07-01 13:55 UTC by swissspidy

## Summary

Ensures that the story title is used as-is for prefilling the post title, so that the titles match.

## Relevant Technical Choices

Uses `$post->post_title` as originally planned instead of `get_the_title()`.

Avoids the `the_title` filter and thus `wptexturize ` and the like from running.

## To-do

## User-facing changes

No texturized post titles.

Users will get `Story - Test`, not `Story &#8211; Test`

## Testing Instructions

---

Fixes #2822

2020-07-01 18:13 UTC, spacedmonkey commented on includes/Admin.php
> +		$post = get_post( $post_id );
Why this every not be a `WP_Post`? Surely the above line `Story_Post_Type::POST_TYPE_SLUG !== get_post_type( $post_id )` would check this?

2020-07-01 18:14 UTC, spacedmonkey commented on includes/Admin.php
> +		if ( ! $post instanceof WP_Post ) {
```suggestion
		if ( ! $post instanceof WP_Post || Story_Post_Type::POST_TYPE_SLUG !== get_post_type( $post ) ) {
```
Maybe?

2020-07-01 18:25 UTC, spacedmonkey requested changes
Smaller tweaks

2020-07-01 20:18 UTC, swissspidy commented on includes/Admin.php
> +		if ( ! $post instanceof WP_Post ) {
Went with something very similar

2020-07-02 10:00 UTC, spacedmonkey approved these changes
LGTM

2020-07-02 11:18 UTC, merged