Story Editor: Improve Keyboard Navigation on Carousel
GoogleForCreators/web-stories-wp pull request #4248
Opened 2020-08-26 22:24 UTC by littlemilkstudio

## Summary
- Adds a focus border around page thumb in collapsed carousel, regular carousel, and page grid view.
- Updates collapsed carousel so only active page thumb is focusable.

## Relevant Technical Choices
Just made the uncollapsed page indicator behave the same as the collapsed page indicator for tabIndex. I think this offloads a little work to the browser instead of doing it manually. Happy to revert tho if there's a preference.

## User-facing changes
- Page indicators in collapsed carousel, uncollaped carousel & grid view now have a blue outline when focused
- Only active page indicator can be focused as long as there's more than 1 page indicator.

## Testing Instructions
- In story editor, tab through page and see that only active page indicator is focusable out of the page indicators, also that it's visually clear that the page indicator is focused.
- In the story editor, click the grid view. In the grid view tab through the page and see that only the active page indicator is focusable out of the page indicators and that it's visually clear that the page indicator is focused.

## Screenshots
<img width="1440" alt="Screen Shot 2020-08-26 at 2 55 56 PM" src="https://user-images.githubusercontent.com/35983235/91362829-846dab80-e7b8-11ea-9f32-98f70567f723.png">
<img width="453" alt="Screen Shot 2020-08-26 at 4 00 39 PM" src="https://user-images.githubusercontent.com/35983235/91362837-87689c00-e7b8-11ea-9fdf-c4f0fd391afe.png">
<img width="381" alt="Screen Shot 2020-08-26 at 4 02 07 PM" src="https://user-images.githubusercontent.com/35983235/91362838-87689c00-e7b8-11ea-919f-8e6f7482ffd7.png">

---

Fixes #4240

2020-08-26 22:59 UTC, barklund approved these changes
Works perfectly - and even reduces code complexity!

2020-08-26 23:18 UTC, mariano-formidable approved these changes
LGTM 👍

2020-08-27 15:38 UTC, dmmulroy commented
This also resolves #3653 in a better way than my PR #4106 does.  I'm happy to close that.

2020-08-27 15:39 UTC, dmmulroy commented
This also resolves #3653 in a better way than my PR #4106 does. I'm happy to close that.

2020-08-27 15:40 UTC, dmmulroy approved these changes

2020-08-27 23:09 UTC, BrittanyIRL approved these changes
LGTM! dig the simplification - applying this update to my PR for keyboard usability in the dashboard.

2020-08-28 01:44 UTC, barklund requested changes
Just a single nit to optimize a bit.

2020-08-28 01:44 UTC, barklund commented on assets/src/edit-story/components/canvas/pagepreview/index.js
> +        <Page tabIndex={tabIndex} {...props}>
Given that `tabIndex` is just passed as-is to the `<Page />`, I think you can completely remove any notion of it in this component and just let it pass through via `props`.

2020-08-28 01:44 UTC, barklund commented on assets/src/edit-story/components/canvas/pagepreview/index.js
> +        <Page tabIndex={tabIndex} {...props}>
You still need to rename [`ariaLabel` to `aria-label`](https://github.com/google/web-stories-wp/blob/main/assets/src/edit-story/components/canvas/carousel/index.js#L418) in the parent <Carousel /> component (yeah, [React is a bit inconsistent with these props](https://reactjs.org/docs/accessibility.html#wai-aria:~:text=Note%20that%20all%20aria%2D*%20HTML%20attributes,as%20they%20are%20in%20plain%20HTML%3A)) to make it pass correctly through.

2020-08-28 01:44 UTC, barklund commented on assets/src/edit-story/components/canvas/carousel/compactIndicator.js
> +  { onClick, isActive, ariaLabel, role, tabIndex },
With the renaming of `ariaLabel` to `aria-label` in `<Carousel />` (as mentioned in the previous comment), you can completely delete this component altogether and just make `Indicator` default export directly!

This component has zero function anymore, that the simple `styled.button` doesn't also have. The sole purpose right now is basically to rename the property, but without that purpose (which is silly anyway), it really doesn't do a thing.

That'll significantly reduce the complexity of this file - all the forward-ref and proptype-stuff can just go out the door!

2020-08-28 01:48 UTC, barklund commented on assets/src/edit-story/components/canvas/pagepreview/index.js
> +        <Page tabIndex={tabIndex} {...props}>
Sorry, I mixed up the two PR's and added some irrelevant comments here. I've removed them and am in the process of re-applying them to #4260, where they belong.

2020-09-03 04:56 UTC, barklund approved these changes

2020-09-03 15:36 UTC, merged