Put eyedropper functionality behind feature flag
GoogleForCreators/web-stories-wp pull request #4266
Opened 2020-08-28 05:38 UTC by sks

- Fixes issue https://github.com/google/web-stories-wp/issues/4081

## Summary

As discribed in #4081, moving the eye dropper in color selection behind a feature flag.

Attaching screenshots:

## To-do

- [ ] Add test cases, will complete once I know I am doing the right thing.

## User-facing changes
#### Before
![Screenshot 2020-08-28 at 10 37 17 AM](https://user-images.githubusercontent.com/570239/91524956-18a55300-e91e-11ea-97ed-963d78226fc4.png)

#### After
- Color picker disabled
![Screenshot 2020-08-28 at 11 03 43 AM](https://user-images.githubusercontent.com/570239/91524995-28249c00-e91e-11ea-852c-6068f44b5c9d.png)
![Screenshot 2020-08-28 at 11 02 06 AM](https://user-images.githubusercontent.com/570239/91525017-31ae0400-e91e-11ea-8573-6d12495701e0.png)

- Color picker enabled
![Screenshot 2020-08-28 at 11 01 47 AM](https://user-images.githubusercontent.com/570239/91525038-38d51200-e91e-11ea-8e3d-bed77d7e637a.png)

![Screenshot 2020-08-28 at 11 01 55 AM](https://user-images.githubusercontent.com/570239/91525045-3e325c80-e91e-11ea-92e6-1af8954856c7.png)

## Testing Instructions

#### Initial state
- Navigate to [Create new story](http://localhost:8899/wp-admin/post-new.php?post_type=web-story)
- Select the background and click on color selection component.
- Verify that there won't be a color picker element available.
#### Enabling Color picker
- Navigate to [stories experimental page](http://localhost:8899/wp-admin/edit.php?post_type=web-story&page=web-stories-experiments)
- Search for flag `EnableColorPicker`
- Tick the checkbox to enable color picker
- Navigate to [Create new story](http://localhost:8899/wp-admin/post-new.php?post_type=web-story)
- Select the background and click on color selection component.
- Verify that there will be a color picker element available.
---

Fixes #4081

2020-08-28 05:38 UTC, sks commented on assets/src/edit-story/components/library/panes/media/local/mediaPane.js
> +              incremental={incrementalSearchDebounceMedia}
This was fixing a typo, not sure if this should be part of this PR

2020-08-28 08:36 UTC, swissspidy commented
Thanks for tackling this!

I thi k the flag should be named „enable eye dropper“, not „enable color picker, because that‘s what it actually does.

2020-08-28 08:52 UTC, sks commented
Done with `enableColorDropper`

2020-08-28 15:32 UTC, swissspidy commented
Sorry for the nitpicking, but eye dropper ≠ color dropper :-)

But no worries, we can tweak it for you before merge to avoid all the back and forth.

2020-09-07 08:52 UTC, spacedmonkey commented on includes/Experiments.php
> +			 * Issue: #32064081
Isn't the issue here #4081

2020-09-07 08:57 UTC, swissspidy commented on assets/src/edit-story/components/colorPicker/currentColorPicker.js
> +          <span />
What's that for? Let's not render unnecessary elements.

Could do `enableEyeDropper  && <EyedropperButton  ....>`

2020-09-15 19:05 UTC, barklund requested changes
It's a really great effort here, just a few comments to get this over the line!

And yes, a simple test would be nice too, but it doesn't have to be anything fancy. Just two unit tests rendering with and without the flag set and validating that `queryByRole('button', {name: /Select color/})` returns correctly is more than fine.

2020-09-15 19:05 UTC, barklund commented on assets/src/edit-story/components/colorPicker/colorPicker.js
> +  const enableEyeDropper = useFeature(Flags.ENABLE_EYE_DROPPER);
Could we not just move this into the `CurrentColorPicker` component? No need to pass it in as a parameter.

2020-09-15 19:05 UTC, barklund commented on assets/src/edit-story/components/colorPicker/currentColorPicker.js
> +      <Body showOpacity={showOpacity} enableEyeDropper={enableEyeDropper}>
Why does the `<Body />` tag need this prop? It doesn't seem to [do anything about it](https://github.com/google/web-stories-wp/blob/1e0cf421b0f4c84e083eec9927fbef4c77dde773/assets/src/edit-story/components/colorPicker/currentColorPicker.js#L55).

2020-09-15 19:05 UTC, barklund commented on assets/src/edit-story/components/colorPicker/currentColorPicker.js
> +          <span />
Yes, this should just be a short-circuit conditional. For future reference, you can simply return `null` when wishing to render nothing.

2020-09-15 19:05 UTC, barklund commented on assets/src/edit-story/components/colorPicker/currentColorPicker.js
> +          />
The button should still be disabled, as it doesn't actually do anything even if the flag is on.

2020-09-15 19:05 UTC, barklund commented on includes/Experiments.php
> +				'description' => __( 'Enable eye dropper.', 'web-stories' ),
It doesn't actually enable the eyedropper, it just shows the (still non-functional) button, so this text might be a bit misleading. Also, _"eyedropper"_ is spelled in [one word](https://en.wiktionary.org/wiki/eyedropper).

2020-09-15 19:05 UTC, barklund commented on assets/src/edit-story/components/colorPicker/currentColorPicker.js
> +        {enableEyeDropper ? (
The layout of the hex input field appears to be a bit off-center without the button.

Comparing your own screenshots:

![with eyedropper](https://user-images.githubusercontent.com/570239/91525017-31ae0400-e91e-11ea-8573-6d12495701e0.png)
![without eyedropper](https://user-images.githubusercontent.com/570239/91525045-3e325c80-e91e-11ea-92e6-1af8954856c7.png)

2020-09-29 14:05 UTC, swissspidy commented
@sks Hi there, any chance you could pick this up again to address the outstanding feedback?

2020-10-07 09:41 UTC, sks commented
@swissspidy : Lots have changed in my personal life, so taking a breakm from this PR, apologies.

Have tried to fix the minor issues, Tasks pending:

- [ ] Add minimal test : https://github.com/google/web-stories-wp/pull/4266#pullrequestreview-488975855
- [ ] Fix the alignment issue reported in https://github.com/google/web-stories-wp/pull/4266#discussion_r488900366

2020-10-27 20:15 UTC, swissspidy commented
Created a new PR #5027 picking this up

2020-10-27 20:15 UTC, closed without merging