PoC to fix horizontal jitter
GoogleForCreators/web-stories-wp pull request #4438
Opened 2020-09-10 06:17 UTC by diegovar

Addresses #4311

2020-09-11 11:08 UTC, swissspidy commented on patches/react-photo-gallery+8.0.0.patch
> +diff --git a/node_modules/react-photo-gallery/dist/react-photo-gallery.esm.js b/node_modules/react-photo-gallery/dist/react-photo-gallery.esm.js
```suggestion
diff --git a/node_modules/react-photo-gallery/dist/react-photo-gallery.esm.js b/node_modules/react-photo-gallery/dist/react-photo-gallery.esm.js
```

2020-09-11 11:11 UTC, swissspidy commented
@cvolzke4 Can we revert #4363 with this?

2020-09-11 11:11 UTC, swissspidy commented
@jhtin I assume #4378 is still needed?

2020-09-14 01:23 UTC, jhtin commented
@swissspidy Not sure if the persistent scrollbar would be needed after this fix: @diegovar could you clarify?

2020-09-14 01:37 UTC, jhtin requested changes, later dismissed
Is it possible to test this?

2020-09-15 04:56 UTC, diegovar commented
> @cvolzke4 Can we revert #4363 with this?

I believe that's unrelated.

2020-09-15 04:56 UTC, diegovar commented
> @swissspidy Not sure if the persistent scrollbar would be needed after this fix: @diegovar could you clarify?

I believe it would.

2020-09-15 04:57 UTC, diegovar commented
> Is it possible to test this?

I don't think it's easy or possible to test this, a it's a mitigation for a very specific edge case that's hard to reproduce on a separate library.

2020-09-15 06:12 UTC, cvolzke4 commented
> @cvolzke4 Can we revert #4363 with this?

Correct, though there isn't any performance benefit to using pure components for PaginatedMediaGallery and/or MediaGallery.

2020-09-15 12:18 UTC, swissspidy approved these changes

2020-09-15 12:29 UTC, merged