Story Editor: Added Section Header Text Sets
GoogleForCreators/web-stories-wp pull request #4537
Opened 2020-09-17 22:34 UTC by littlemilkstudio

## Summary
Adds text sets under `Section Header` category in this design file:
https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=837%3A3585

## User-facing changes
NA

## Testing Instructions
Enable the text sets flag in experiments and see the new text sets in the story editor.

---

Partial for #4078

2020-09-18 16:52 UTC, BrittanyIRL approved these changes
Awesome! I see 8 new text sets. 

Looks great. I saw two fonts that I think are slightly off but overall this looks great and works well for me in the editor.
![Screen Shot 2020-09-18 at 9 51 30 AM](https://user-images.githubusercontent.com/10720454/93624048-8f20f800-f994-11ea-9a41-1176cdc7972b.png)

2020-09-18 16:52 UTC, BrittanyIRL commented on assets/src/edit-story/components/library/panes/text/textSets/raw/section_header.json
> +            "family": "Poppins",
I believe this font should be Merriweather not Poppins
(figma)
<img width="312" alt="Screen Shot 2020-09-18 at 9 42 30 AM" src="https://user-images.githubusercontent.com/10720454/93623327-6d734100-f993-11ea-9c87-3c518eb5c2d2.png">

(editor)
![Screen Shot 2020-09-18 at 9 42 44 AM](https://user-images.githubusercontent.com/10720454/93623330-6e0bd780-f993-11ea-9f28-b5be0e181041.png)

2020-09-18 16:52 UTC, BrittanyIRL commented on assets/src/edit-story/components/library/panes/text/textSets/raw/section_header.json
> +            "family": "Nunito Sans",
And this is just "Nunito" not "Sans"

(figma)
<img width="294" alt="Screen Shot 2020-09-18 at 9 46 46 AM" src="https://user-images.githubusercontent.com/10720454/93623721-030ed080-f994-11ea-9067-70efcc559972.png">

(editor)
![Screen Shot 2020-09-18 at 9 46 36 AM](https://user-images.githubusercontent.com/10720454/93623735-0bffa200-f994-11ea-9926-b0407a10a990.png)

2020-09-18 21:34 UTC, dmmulroy approved these changes
Agree / @BrittanyIRL on the differences but otherwise lgtm

2020-09-21 08:32 UTC, miina requested changes
Same here as well as with other sets -- otherwise looks good but the margin between the title and the paragraph varies among the sets whereas in Figma it's fixed 16px

- There are also some minor horizontal alignment issues -- in Figma the sets have 40px from both sides, in the editor it varies a bit, for example:
<img width="304" alt="Screenshot 2020-09-21 at 11 31 11" src="https://user-images.githubusercontent.com/3294597/93746632-be826f80-fbf5-11ea-90f8-69aedbc391a0.png">

2020-09-23 20:59 UTC, littlemilkstudio commented
> Same here as well as with other sets -- otherwise looks good but the margin between the title and the paragraph varies among the sets whereas in Figma it's fixed 16px
> 
> * There are also some minor horizontal alignment issues -- in Figma the sets have 40px from both sides, in the editor it varies a bit, for example:
> 
> <img alt="Screenshot 2020-09-21 at 11 31 11" width="304" src="https://user-images.githubusercontent.com/3294597/93746632-be826f80-fbf5-11ea-90f8-69aedbc391a0.png">

yea spacing was a bit hard. I went off the figma file I was referencing and put everything at the x & y coordinate it specified then once the entire group was positioned, dragged the entire group to proper position in the story. I also think our editor positions bounding boxes around text slightly different than figma, so if something looked off I just tried to manually adjust it as best I could.

If there's a better method I'd be happy to do it but this is the best I could come up with. 

Something to note with going 16px from the bottom of the text bounding box is the difference in bottom for figma vs our app.

**our app**
<img width="304" alt="93746632-be826f80-fbf5-11ea-90f8-69aedbc391a0" src="https://user-images.githubusercontent.com/35983235/94069031-3050e980-fdad-11ea-8c1c-7e404c8e1392.png">

**Figma**
<img width="230" alt="Screen Shot 2020-09-23 at 2 57 42 PM" src="https://user-images.githubusercontent.com/35983235/94069065-3e9f0580-fdad-11ea-91c5-a7142ab83e66.png">
 
this makes 16px from the bottom of the bounding box visually different between figma and the editor. I thoughts tops were more reliable, but still needed some manual approximation to acct for difference imo

2020-09-24 07:35 UTC, miina commented
@littlemilkstudio One option could be to create a shape of 16px which could be used as a reference to measure the distance of each set and then removed once it's positioned. WDYT -- would that work / be too complicated?

2020-09-24 17:27 UTC, littlemilkstudio commented
@miina yea that's not a bad approach, but wouldn't it still involve some approximation? because there's still space between the bottom of the text and the bottom of the bounding box in figma that we can't get an exact value for and we'd need to line the 16px shape to the bottom of where the figma bounding box _would_ be?

Or am I misunderstanding the suggestion?

2020-09-24 18:42 UTC, miina commented
> because there's still space between the bottom of the text and the bottom of the bounding box in figma that we can't get an exact value for and we'd need to line the 16px shape to the bottom of where the figma bounding box would be?

Yep, true, it still wouldn't be precise but it might give a bit better reference.

Anyway, if you feel like that's OK as it is then let's just merge and Sam can do the UAT later.

2020-09-24 18:43 UTC, miina approved these changes
LGTM -- let's follow up with adjustments after UAT if needed.

2020-09-29 17:03 UTC, merged