[WIP] Allow showing admin bar on frontend
GoogleForCreators/web-stories-wp pull request #4546
Opened 2020-09-18 17:29 UTC by swissspidy

## Summary

If users prefer to display the toolbar on the frontend, they should be able to see it also when viewing stories.

## Relevant Technical Choices

## To-do

## User-facing changes

If enabled in the user profile, the admin toolbar will be displayed on the frontend.

## Testing Instructions

---

Depends on #4513

2020-09-23 21:56 UTC, swissspidy commented
@westonruter @schlessera @spacedmonkey While we're at it... I figured it might be nice to allow displaying the admin bar on the frontend.

2020-09-24 12:02 UTC, spacedmonkey commented on tests/phpunit/tests/Story_Post_Type.php
> -	/**
Can we add some unit tests for this?

2020-09-24 12:06 UTC, spacedmonkey commented
If we have unit tests this, I am happy with this change

2020-09-24 12:29 UTC, swissspidy commented on includes/Story_Renderer/HTML.php
> +	 * since Web Stories are theme-independent and requiree
```suggestion
	 * since Web Stories are theme-independent and require
```

2020-09-24 12:29 UTC, swissspidy commented on includes/Story_Renderer/HTML.php
> +
```suggestion
```

2020-09-24 14:23 UTC, schlessera commented
You should consider adding the `data-ampdevmode` attribute to the admin bar (if it wasn't already added by the AMP plugin). This will exclude the admin bar from being checked for validation errors. Otherwise, you will most likely hit "Excessive CSS" validation errors or others.

Right now, the attribute itself will throw a validation error, but that is planned to be changed.

See https://github.com/ampproject/amp-wp/issues/1921

2020-09-24 14:31 UTC, swissspidy commented
@schlessera Yep, this is covered by #4513 (on which this PR here is based)

2020-09-25 13:14 UTC, spacedmonkey approved these changes
👍

2020-09-26 03:12 UTC, westonruter requested changes
I'm getting PHP warnings:

```
PHP Warning:  DOMDocumentFragment::appendXML(): 		 in /app/public/content/plugins/web-stories/includes/Story_Renderer/HTML.php on line 330
PHP Warning:  DOMDocumentFragment::appendXML(): 		^ in /app/public/content/plugins/web-stories/includes/Story_Renderer/HTML.php on line 330
PHP Warning:  DOMDocumentFragment::appendXML():                       ^ in /app/public/content/plugins/web-stories/includes/Story_Renderer/HTML.php on line 330
PHP Warning:  DOMDocumentFragment::appendXML(): &lt;link data-ampdevmode rel='stylesheet' id='admin-bar-css'  href='https://wordpre in /app/public/content/plugins/web-stories/includes/Story_Renderer/HTML.php on line 330
PHP Warning:  DOMDocumentFragment::appendXML(): &lt;link data-ampdevmode rel='stylesheet' id='dashicons-css'  href='https://wordpre in /app/public/content/plugins/web-stories/includes/Story_Renderer/HTML.php on line 330
PHP Warning:  DOMDocumentFragment::appendXML(): Entity: line 17: parser error : chunk is not well balanced in /app/public/content/plugins/web-stories/includes/Story_Renderer/HTML.php on line 330
PHP Warning:  DOMDocumentFragment::appendXML(): Entity: line 1: parser error : Couldn't find end of Start Tag link line 1 in /app/public/content/plugins/web-stories/includes/Story_Renderer/HTML.php on line 330
PHP Warning:  DOMDocumentFragment::appendXML(): Entity: line 1: parser error : Specification mandate value for attribute data-ampdevmode in /app/public/content/plugins/web-stories/includes/Story_Renderer/HTML.php on line 330
PHP Warning:  DOMDocumentFragment::appendXML(): Entity: line 1: parser error : attributes construct error in /app/public/content/plugins/web-stories/includes/Story_Renderer/HTML.php on line 330
PHP Warning:  DOMDocumentFragment::appendXML(): Entity: line 2: parser error : Couldn't find end of Start Tag link line 2 in /app/public/content/plugins/web-stories/includes/Story_Renderer/HTML.php on line 330
PHP Warning:  DOMDocumentFragment::appendXML(): Entity: line 2: parser error : Specification mandate value for attribute data-ampdevmode in /app/public/content/plugins/web-stories/includes/Story_Renderer/HTML.php on line 330
PHP Warning:  DOMDocumentFragment::appendXML(): Entity: line 2: parser error : attributes construct error in /app/public/content/plugins/web-stories/includes/Story_Renderer/HTML.php on line 330
PHP Warning:  DOMNode::appendChild(): Document Fragment is empty in /app/public/content/plugins/web-stories/includes/Story_Renderer/HTML.php on line 332
```

And no admin bar appears:

![image](https://user-images.githubusercontent.com/134745/94329591-2e378800-ff71-11ea-85f1-299335a207e2.png)

2020-09-26 03:39 UTC, westonruter commented
Mostly fixed by 973c69d with one exception: the AMP menu lacks the icon.

![image](https://user-images.githubusercontent.com/134745/94329346-0e06c980-ff6f-11ea-9a0d-a87153828412.png)

This is because it lacks `amp-icons.css`.

2020-09-26 03:50 UTC, westonruter commented
OK, that's fixed now with 2dffaeb:

![image](https://user-images.githubusercontent.com/134745/94329525-89b54600-ff70-11ea-957b-f85770ff850d.png)

See corresponding logic in the AMP plugin: https://github.com/ampproject/amp-wp/blob/806794efd3a04ce43e8f41357cf8f8692495218d/includes/amp-helper-functions.php#L129-L138

2020-09-26 04:00 UTC, westonruter commented
Nevertheless, I don't think what I added is sufficient because it's only accounting for a one-off case for the AMP plugin. What about other plugins that add admin bar menu items? For example, Yoast is broken:

![image](https://user-images.githubusercontent.com/134745/94329632-a3a35880-ff71-11ea-95fe-7d10d2638fb6.png)

I assume Site Kit would also be broken. 

I think it needs to do all enqueued stylesheets coming from `admin_bar_init`.

Something else that is needed is the admin bar needs to _continue_ to be omitted when the story is shown in an `amp-story-player`. It doesn't look good now:

![image](https://user-images.githubusercontent.com/134745/94329675-0dbbfd80-ff72-11ea-8aa0-334ee5bc0f01.png)

2020-09-26 04:07 UTC, westonruter commented
> Something else that is needed is the admin bar needs to _continue_ to be omitted when the story is shown in an `amp-story-player`. It doesn't look good now:

Fixed in 748bde8.

2020-09-26 04:28 UTC, westonruter commented
> Nevertheless, I don't think what I added is sufficient because it's only accounting for a one-off case for the AMP plugin. What about other plugins that add admin bar menu items? For example, Yoast is broken:

Unfortunately just doing `wp_styles()->do_items()` is not going to fix the problem for Yoast. The reason is that it is [doing this](https://github.com/Yoast/wordpress-seo/blob/b67ca925b5e8fad8414cdd283385e69234664518/inc/class-wpseo-admin-bar-menu.php#L130-L131):

```php
add_action( 'wp_enqueue_scripts', [ $this, 'enqueue_assets' ] );
add_action( 'admin_enqueue_scripts', [ $this, 'enqueue_assets' ] );
```

It would work automatically if it instead did:

```php
add_action( 'admin_bar_init', [ $this, 'enqueue_assets' ] );
```

Nevertheless, Site Kit is [doing the same](https://github.com/google/site-kit-wp/blob/66cfcd60f91e1419044fcf0f6c49b5101b9f8658/includes/Core/Admin_Bar/Admin_Bar.php#L110-L111) as Yoast:

```php
add_action( 'admin_enqueue_scripts', $admin_bar_callback, 40 );
add_action( 'wp_enqueue_scripts', $admin_bar_callback, 40 );
```

Since both Site Kit and Yoast are doing the same thing, I'm not sure what alternative we have to just going ahead and doing `wp_enqueue_scripts()`. The challenge then is going to be omitting the stylesheets that are not intended for styling the admin bar. One way to address this could be after calling `wp_enqueue_scripts()` to loop over `wp_styles()->queue` and dequeue any stylesheet that neither a dependency _of_ nor _for_ `admin-bar`. The AMP plugin uses this to figure out what stylesheets to automatically add `data-ampdevmode` attributes to: https://github.com/ampproject/amp-wp/blob/806794efd3a04ce43e8f41357cf8f8692495218d/includes/class-amp-theme-support.php#L1481-L1499

Something else to keep in mind is that there are _scripts_ that the admin bar depends on, especially plugins. Site Kit and Jetpack both will enqueue scripts that are needed or else some functionality in the admin bar that they add in PHP will either be broken or limited in functionality. See also the AMP plugin logic for marking admin bar scripts for dev mode: https://github.com/ampproject/amp-wp/blob/806794efd3a04ce43e8f41357cf8f8692495218d/includes/class-amp-theme-support.php#L1481-L1499

You may want to refer to how the admin bar is added to the legacy AMP Reader mode template. It actually goes ahead and calls `wp_print_head_scripts()` and `wp_print_footer_scripts()`: https://github.com/ampproject/amp-wp/blob/806794efd3a04ce43e8f41357cf8f8692495218d/includes/amp-post-template-functions.php#L30-L32

2020-09-26 08:13 UTC, swissspidy commented
Thanks a lot for digging into this @westonruter! I‘m gonna try the printing scripts option

2020-09-28 20:28 UTC, swissspidy commented
> One way to address this could be after calling `wp_enqueue_scripts()` to loop over `wp_styles()->queue` and dequeue any stylesheet that neither a dependency of nor for `admin-bar`

Site Kit's [admin bar CSS](https://github.com/google/site-kit-wp/blob/ecd36f47933676253ce3467cbc49bca203a1c6e0/includes/Core/Assets/Assets.php#L604-L610) doesn't have `admin-bar` as its dependency, so I don't think this is viable.

2020-09-28 21:20 UTC, westonruter commented
That seems like an improvement to be made with Site Kit then. Nevertheless, there's going to be many plugins that don't do this either. 

It seems the scripts and styles just need to be printed in their entirety? In Jetpack we've had to manually add the `data-ampdevmode` attribute via the `style_loader_tag` filter, for example. Site Kit does this also, I believe, so it doesn't need have the dependency.

The concern is stylesheets coming from the theme and plugins which aren't related to the admin bar.

2020-09-28 21:23 UTC, swissspidy commented
Yup, looks like it. Unrelated CSS might of course mess  with the story content, so I suppose we have to make a tradeoff here.

2020-09-30 15:19 UTC, spacedmonkey commented
Could we make this simpler and not support plugins that add options to the admin bar? Deregister all menus items in the admin bar that are not core. Than have a filter to white list what we want. So maybe, yoast, jetpack and amp plugin can be support. 

I feel like enqueueing scripts and styles that any old plugin put on the page is going complete mess. 

I might be wrong here.

2020-09-30 18:58 UTC, swissspidy commented
That'd could be a way to work around the plugin, but also requires some work (remove all menu items), and might confuse users ("where's my AMP plugin menu item?!?!")

Not sure loading all these scripts or styles is really going to be messy.

2021-07-01 13:32 UTC, closed without merging