Story Editor: Added Editorial Text Sets
GoogleForCreators/web-stories-wp pull request #4552
Opened 2020-09-18 19:24 UTC by littlemilkstudio

## Summary
Adds text sets under `Editorial` category in this design file:
https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=837%3A3585

## User-facing changes
NA

## Testing Instructions
Enable the text sets flag in experiments and see the new text sets in the story editor.

---

Partial for #4078

2020-09-18 20:12 UTC, carlos-kelly commented
I tested all of them and they place and look good. 

<img width="752" alt="Screen Shot 2020-09-18 at 3 02 40 PM" src="https://user-images.githubusercontent.com/1738349/93641125-5fd4b000-f9c1-11ea-8cfd-5de34b7b7dd0.png">

2020-09-18 20:13 UTC, carlos-kelly approved these changes

2020-09-21 07:38 UTC, miina requested changes
Generally looks good, some details:

- In Figma, in addition to docking to the bottom, all the text sets are also horizontally centered (40px room from both sides). In the PR, some text sets seem to be centered but not all.

- On some presets, the heading is not exactly the same length as the text area which makes the heading not 100% centered compared to the text, it's almost unnoticeable but if it's easy to do, let's make the headings match the length of the paragraph so that it would be 100% centered (in case of centered titles). For example:
<img width="253" alt="Screenshot 2020-09-21 at 10 26 33" src="https://user-images.githubusercontent.com/3294597/93741635-1799d580-fbed-11ea-94f1-7d65738ad16e.png">

- In some cases, Figma has more room between the title and the paragraph than in the text sets. It looks like the room in Figma is always 16px, it differs among the Text Sets a bit. E.g. these two sets have a different margin between the title and the paragraph:
<img width="338" alt="Screenshot 2020-09-21 at 10 36 03" src="https://user-images.githubusercontent.com/3294597/93742222-08675780-fbee-11ea-8a81-57a653491085.png">

2020-09-24 22:00 UTC, littlemilkstudio commented
@miina updated all of these to 332px width with 40px margin. also did a hard 16px margin from the text box no matter what and made a note of it in the text sets slack channel for sam.

Lemme know if this is the approach we wanna take from now on after seeing it or wanna alter at all

2020-09-25 10:03 UTC, miina approved these changes
LGTM!

Since we can reliably use the consistent 16px only between the elements and we can't really manually detect the different margins that Figma elements have then this approach seems to make sense. Looks good in testing.

Now all the sets are positioned precisely in the same place as well 👍

2020-09-29 16:20 UTC, merged