Implements tooltips
GoogleForCreators/web-stories-wp pull request #469
Opened 2020-03-04 21:34 UTC by wassgha

Closes #66 

![ezgif com-video-to-gif (19)](https://user-images.githubusercontent.com/591655/75923442-ece75b80-5e19-11ea-804d-ee1371188a51.gif)

### Changes
- Implements a thin wrapper on top of `Material UI` tooltips
- Adds a small utility for converting shortcuts to use user-displayed symbols
- Adds storybook entry

2020-03-04 21:50 UTC, swissspidy commented
Could you make all the labels translatable?

2020-03-04 22:28 UTC, barklund commented
This clearly doesn't tree-shake. [+27.9 kB is a lot](https://github.com/google/web-stories-wp/pull/469#issuecomment-594862251) just for tooltips! I'd even say it's too much.

2020-03-04 22:37 UTC, swissspidy commented
Have only skimmed through that page but perhaps we need to apply some changes for tree-shaking to work? https://material-ui.com/guides/minimizing-bundle-size/

2020-03-04 23:36 UTC, wassgha commented
Hmm that didn't work :/ What do we think? Continue playing with it or implement our own?

2020-03-05 04:01 UTC, wassgha commented
@barklund @swissspidy Update on this: it seems like that's actually tree shaken, the issue is that `material-ui` is using [Popper](https://github.com/popperjs/popper-core) behind the scenes (**7kb**) to make sure the tooltips are positioned correctly (automatically prevents clipping/overflow). Do we think we want that feature or is static positioning enough for our use case? In both case, this doesn't rule out using material UI for other components since tree shaking seems to be working as intended.

2020-03-05 07:08 UTC, swissspidy commented
Thanks for checking!

I think static positioning is enough for now.

2020-03-05 13:16 UTC, swissspidy commented on assets/src/edit-story/components/keyboard/index.js
> +export function prettifytShortcut(shortcut) {
```suggestion
export function prettifyShortcut(shortcut) {
```

Also wondering if we should use `<kbd>` for displaying the shortcuts. Seems to be only semantic though 🤔

2020-03-05 21:34 UTC, barklund commented on package.json
> +    "@material-ui/core": "^4.9.5",
This can be reverted now, no? Or do we still want it in?

2020-03-05 22:12 UTC, wassgha commented on package.json
> +    "@material-ui/core": "^4.9.5",
Removed :))

2020-03-05 23:04 UTC, dvoytenko requested changes

2020-03-05 23:04 UTC, dvoytenko commented on assets/src/edit-story/components/keyboard/index.js
> +    .replace('backspace', '⌫')
I've replaced "backspace" and "del" with `delete`. See https://github.com/google/web-stories-wp/blob/master/assets/src/edit-story/components/keyboard/keys.js. I suggest we use the same naming here. Otherwise, we'd have to support del/backspace multiple times.

2020-03-05 23:04 UTC, dvoytenko commented on assets/src/edit-story/components/tooltip/index.js
> +  display: inline-block;
`inline-block` should almost never be used. Can we just leave it up to the caller? I assume most would want to apply some form of flex item.

2020-03-05 23:04 UTC, dvoytenko commented on assets/src/edit-story/components/tooltip/index.js
> +const Tooltip = ({
This sounds more like a `WithTooltip` to me. Also, why not just `function Tooltip(...)`?

2020-03-05 23:04 UTC, dvoytenko commented on assets/src/edit-story/components/tooltip/index.js
> +const Tip = styled.div`
Please comment here that the Tooltip is positioned via `position:fixed` + `transform`.

2020-03-05 23:04 UTC, dvoytenko commented on package.json
> +  "keywords": [
Seems like we keep threshing this array back and force :)

2020-03-06 16:05 UTC, dvoytenko approved these changes

2020-03-06 16:06 UTC, dvoytenko submitted a review, later dismissed

2020-03-06 16:06 UTC, dvoytenko commented on assets/src/edit-story/components/tooltip/index.js
> +  onMouseEnter = () => {},
Per Paul's direction: should we just quickly switch it to `onPointerEnter`

2020-03-09 11:25 UTC, swissspidy approved these changes
Generally looks good 👍 

Haven't fully tested screen reader support though. But we can always iterate.

2020-03-09 12:00 UTC, spacedmonkey approved these changes
👍

2020-03-09 15:55 UTC, merged