Dashboard: add support link to navigation
GoogleForCreators/web-stories-wp pull request #4748
Opened 2020-09-29 16:13 UTC by BrittanyIRL

## Summary
Adds external support link to side nav in dashboard

## Relevant Technical Choices
- Update link in constants, take `inProgress` off support so it shows up in menu

## To-do

## User-facing changes

- Now you can see and click on 'support' in the dashboard side nav
<img width="331" alt="Screen Shot 2020-09-29 at 9 05 13 AM" src="https://user-images.githubusercontent.com/10720454/94584437-75ed3680-0233-11eb-9a73-bbe9ffeb02bc.png">

## Testing Instructions
- Verify that you see the above 'support' menu item and that clicking it takes you here: https://wordpress.org/support/plugin/web-stories/

---

Addresses #1519

2020-09-29 16:18 UTC, carlos-kelly approved these changes

2020-09-29 18:41 UTC, dmmulroy approved these changes

2020-10-02 16:21 UTC, BrittanyIRL commented
After discussion with Omar and Pascal I've added to this: 
- click tracking for external links on the side nav (only support at this time) 
- opening external links as a new tab on the side nav (only support at this time)

2020-10-02 16:35 UTC, carlos-kelly commented on assets/src/dashboard/components/pageStructure/index.js
> +                  })}
I believe this could fail if this results to `path.isExternal && {...}` actually becomes `false`.

We should do `path.isExternal ? { ... } : {}`

2020-10-02 16:35 UTC, littlemilkstudio approved these changes

2020-10-02 16:36 UTC, carlos-kelly requested changes
One comment on the spread, otherwise great.

2020-10-02 16:42 UTC, carlos-kelly reviewed
<img width="620" alt="Screen Shot 2020-10-02 at 11 41 34 AM" src="https://user-images.githubusercontent.com/1738349/94948033-44c76d00-04a4-11eb-9f2d-9ffa89c27787.png">

I'm seeing the right tags but it's not opening in a new tab

2020-10-02 17:28 UTC, swissspidy commented
> I'm seeing the right tags but it's not opening in a new tab

If you have opted in to telemetry, the `trackClick` handler will do a `document.location = ...` after the tracking happened (as per https://support.google.com/analytics/answer/7478520?hl=en)

https://github.com/google/web-stories-wp/blob/9aa3bdefa7edd906b48ec4c8c18391a1bb5180ec/assets/src/tracking/trackClick.js#L49-L51

2020-10-02 18:11 UTC, BrittanyIRL commented
> > I'm seeing the right tags but it's not opening in a new tab
> 
> If you have opted in to telemetry, the `trackClick` handler will do a `document.location = ...` after the tracking happened (as per https://support.google.com/analytics/answer/7478520?hl=en)
> 
> https://github.com/google/web-stories-wp/blob/9aa3bdefa7edd906b48ec4c8c18391a1bb5180ec/assets/src/tracking/trackClick.js#L49-L51

Thanks for this, @swissspidy  

I ended up swapping out `trackClick` for `trackEvent` in this use case because we always want a new tab to open and I didn't want to change the `trackClick` code to only `preventDefault()` when a url is present as well as conditionally set the `document.location` in the `finally` block. If we want to do that I'd feel better about that being its own ticket? This seems like an isolated use case where we always need that new tab to open. 

Thoughts?

2020-10-02 18:19 UTC, carlos-kelly approved these changes

2020-10-05 18:01 UTC, csossi commented
Verified in QA

2020-10-06 00:16 UTC, merged