Simplify usage of assets CDN URL
GoogleForCreators/web-stories-wp pull request #5898
Opened 2021-01-12 15:16 UTC by swissspidy

## Summary

Companion PR: #5897

Updates how `WEBSTORIES_CDN_URL` is constructed in the plugin, leveraging the changes on the CDN-side to  improve maintenance.

This is an important step toward full release automation.

Development builds will continue to load images from `public/static/main` like today, whereas stable releases will load them from `public/static/<version>`, where `<version>` is an unsigned integer, e.g.  1, 2, 3, etc.

## Relevant Technical Choices

Redirects have been added on the CDN to ensure old plugin versions continue to work as expected.

## To-do

N/A

## User-facing changes

N/A

## Testing Instructions

N/A

---

Fixes #4752
See #5191

2021-01-13 11:09 UTC, spacedmonkey commented
The percy screenshot seems to be validly broken.

2021-01-13 11:22 UTC, spacedmonkey requested changes
Changes seem pretty good.  But I will not approve until I understand why the screenshot is failing.

2021-01-13 11:31 UTC, swissspidy commented
@spacedmonkey just some hiccup, there's no missing image now that I've re-run the tests

https://percy.io/google/web-stories-wp-e2e/builds-next/8359342/changed/475516514

2021-01-14 11:01 UTC, swissspidy commented
@spacedmonkey Can you review again?

2021-01-14 13:02 UTC, spacedmonkey approved these changes
Looks good to me.

2021-01-14 13:12 UTC, merged