Widget: Skip flakey customizer e2e test
GoogleForCreators/web-stories-wp pull request #6983
Opened 2021-04-01 17:16 UTC by spacedmonkey

## Context

## Summary

Unable to fix test, skip it for now. 

## Relevant Technical Choices

## To-do

## User-facing changes

## Testing Instructions

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [ ] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Reviews

### Does this PR have a security-related impact?

### Does this PR change what data or activity we track or use?

### Does this PR have a legal-related impact?

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6879

2021-04-02 10:26 UTC, swissspidy commented on packages/e2e-tests/src/specs/wordpress/widget.js
> +  describe.skip('Customizer', () => {
you'll need to `// eslint-ignore-next-line jest/no-disabled-tests` and provide a reason why it was disabled.

Ideally with a link to the ticket to address it.

```js
// Disable reason: Flakey test that needs to be investigated.
// See https://github.com/google/web-stories-wp/issues/6879
// eslint-disable-next-line jest/no-disabled-tests
```

2021-04-02 10:26 UTC, swissspidy requested changes
lint error

2021-04-06 10:12 UTC, spacedmonkey commented on packages/e2e-tests/src/specs/wordpress/widget.js
> +  describe.skip('Customizer', () => {
```suggestion
  // Disable reason: Flakey test that needs to be investigated.
  // See https://github.com/google/web-stories-wp/issues/6879
  // eslint-disable-next-line jest/no-disabled-tests
  describe.skip('Customizer', () => {
```

2021-04-06 13:29 UTC, swissspidy approved these changes

2021-04-06 13:29 UTC, merged