Don't set resource width/height to inserted element size
GoogleForCreators/web-stories-wp pull request #7476
Opened 2021-05-10 23:48 UTC by choumx

## Context

## Summary

## Relevant Technical Choices

## To-do

## User-facing changes

## Testing Instructions

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [ ] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Reviews

### Does this PR have a security-related impact?

### Does this PR change what data or activity we track or use?

### Does this PR have a legal-related impact?

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [ ] I have added a matching `Type: XYZ` label to the PR

---

Fixes #

2021-05-11 07:55 UTC, swissspidy commented
The goal of `createElementForCanvas` -> `getElementProperties` -> `getInsertedElementSize` is to ensure media elements are added to the canvas with reasonable size and correct aspect ratio, also ensuring a reasonable maximum size. (That whole logic could really use some documentation and tests)

Setting the element's width and height accordingly makes sense, but I also don't see why the resource was updated there too. In this context, it should be considered immutable.

So +1 to this change here.

2021-05-11 10:00 UTC, spacedmonkey commented
> to ensure media elements are added to the canvas with reasonable size and correct aspect ratio, also ensuring a reasonable maximum size

I believe that video are not being inserted at a reasonable maximum size. Take this screenshot from a 4k video a dragged into canvas. 

<img width="1746" alt="Screenshot 2021-05-11 at 10 57 19" src="https://user-images.githubusercontent.com/237508/117797464-f81cef00-b247-11eb-8575-6ed9a91ee75c.png">

After the upload/transcode is complete is resizes to a more reasonable size. 

<img width="1746" alt="Screenshot 2021-05-11 at 10 58 10" src="https://user-images.githubusercontent.com/237508/117797540-09fe9200-b248-11eb-9b8a-0be0992ac0d6.png">

I know this is somewhat unrelated, but it is a behaviour that has bugged me in my testing and think should be changed.

2021-05-11 10:06 UTC, spacedmonkey commented
This change looks perfectly reasonable to me. I don't understand the original reasoning why it was like it was.

2021-05-11 11:40 UTC, swissspidy commented
> I believe that video are not being inserted at a reasonable maximum size. Take this screenshot from a 4k video a dragged into canvas.
> I know this is somewhat unrelated, but it is a behaviour that has bugged me in my testing and think should be changed.

Yeah this is something that was introduced with the video optimization work at some point. It's just odd because the code path there is the same. It's been bugging me a bit too and I'll create a ticket to keep track of it.

2021-05-11 12:47 UTC, spacedmonkey commented
This PR seems to fix the issue I documented in https://github.com/google/web-stories-wp/pull/7476#issuecomment-838195053. 

<img width="1746" alt="Screenshot 2021-05-11 at 13 45 54" src="https://user-images.githubusercontent.com/237508/117817273-56090100-b25f-11eb-8f13-f8e0b7b0a6ec.png">

2021-05-11 15:17 UTC, dreamofabear commented
Cool, I'll add some unit tests for `getElementProperties()`.

2021-05-11 15:31 UTC, littlemilkstudio approved these changes
makes sense to me. thanks for looking into this

2021-05-12 09:58 UTC, spacedmonkey approved these changes
Did some testing locally. This seems to fix some other problems. Let's get this merged.

2021-05-12 11:22 UTC, swissspidy requested changes
The change itself looks good.

However, looking at the Percy snapshots, an inserted image now appears stretched. So there seems to be a regression here.

2021-05-13 22:46 UTC, choumx commented
Hmm, looks like it's this test that showed the diff: https://github.com/google/web-stories-wp/blob/aabae03b767542e8c997325bec490079fc901706/assets/src/edit-story/components/inspector/karma/prepublishSelect.karma.js#L319-L352

I can't repro when trying to insert images manually in a variety of ways, so this might be a flake. I'll try rerunning.

2021-05-14 08:17 UTC, swissspidy commented
> Hmm, looks like it's this test that showed the diff:
> 
> https://github.com/google/web-stories-wp/blob/aabae03b767542e8c997325bec490079fc901706/assets/src/edit-story/components/inspector/karma/prepublishSelect.karma.js#L319-L352
> 
> I can't repro when trying to insert images manually in a variety of ways, so this might be a flake. I'll try rerunning.

Hmm it doesn't help that the `resource` in that test doesn't have any dimensions.

What if you add 

```
width: 640, 
height: 529, 
```

to the resource?

2021-05-17 19:24 UTC, swissspidy approved these changes
Image isn't stretched anymore in the test 👍

2021-05-18 21:35 UTC, csossi commented
Verified in QA

2021-05-18 22:36 UTC, merged