Stickers: Add Human Readable Names
GoogleForCreators/web-stories-wp pull request #7491
Opened 2021-05-11 19:25 UTC by littlemilkstudio

## Context
Adds human readable names to stickers. This improves accessibility for them and the layers panel

## Summary
Adds `<title>` element to all sticker svgs for improved accessibility and also improves the layers panel with human readable names for the stickers.

## Relevant Technical Choices
NA

## To-do
NA

## User-facing changes
 Stickers used in the templates should now have a more readable name than `Sticker`
 
<img width="1033" alt="Screen Shot 2021-05-11 at 1 24 04 PM" src="https://user-images.githubusercontent.com/35983235/117872690-39b79500-b25c-11eb-99bf-65c992127e29.png">

## Testing Instructions
Verify user facing changes shown above in layers panel

### QA
Follow Testing instructions above

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [x] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Reviews

### Does this PR have a security-related impact?

### Does this PR change what data or activity we track or use?

### Does this PR have a legal-related impact?

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [ ] I have added a matching `Type: XYZ` label to the PR

---

Fixes #7425

2021-05-11 20:17 UTC, BrittanyIRL commented on packages/stickers/package.json
> +    "@web-stories-wp/i18n": "*"
Was this intentional?

2021-05-11 20:19 UTC, littlemilkstudio commented on packages/stickers/package.json
> +    "@web-stories-wp/i18n": "*"
yea, it needs this dep to have access to `__(...)` in the stickers for their titles

2021-05-11 23:13 UTC, samwhale approved these changes
Noice

2021-05-11 23:13 UTC, samwhale commented on docs/external-template-creation.md
> +Remove extraneous attributes on the base `svg` component and make sure your component takes a `style` property that it applies to the base svg element. Also make sure to remove any explicit `height`
👍

2021-05-12 07:27 UTC, swissspidy commented on packages/stickers/src/beauty/cta.js
> +const title = __('Heart', 'web-stories');
Let's use `_x()` everywhere so translators have more context.

```suggestion
const title = _x('Heart', 'sticker name', 'web-stories');
```

2021-05-12 07:28 UTC, swissspidy requested changes
Strings should use `_x()` to have context.

2021-05-12 07:28 UTC, swissspidy commented
There seem to be some unwanted changes to the lock file, breaking webpack builds.

2021-05-13 20:28 UTC, embarks approved these changes

2021-05-14 09:55 UTC, spacedmonkey approved these changes

2021-05-17 08:07 UTC, swissspidy approved these changes

2021-05-17 08:07 UTC, merged