Pre-Publish Checklist: Video Optimization displays thumbnail for missing poster
GoogleForCreators/web-stories-wp pull request #7676
Opened 2021-05-21 16:15 UTC by littlemilkstudio

## Context
Part of video optimization in PPC work

## Summary
Conditionally renders video thumbnail depending on if there's a poster image.

Before, it would display the alt and not look good
![119059308-5710ff80-b9d0-11eb-8fe0-ad0b7a3f8757](https://user-images.githubusercontent.com/35983235/119167390-0a074a80-ba1d-11eb-90f5-d57504a37bd0.png)

## Relevant Technical Choices
NA

## To-do
NA

## User-facing changes
In the pre-publish checklist check for unoptimized videos:
If a user uploads a video without a poster image, the poster image thumbnail should not display anymore.

## Testing Instructions
-> Open Settings
-> Turn off auto optimize videos
-> Navigate to the editor
-> Drag a large video onto the canvas without a poster image
-> Navigate to the pre-publish checklist
-> If the check should never show the alt text in the thumbnail. Just either the video thumbnail with an image or no thumbnail

### QA
Follow testing instructions above.

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [x] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Reviews

### Does this PR have a security-related impact?

### Does this PR change what data or activity we track or use?

### Does this PR have a legal-related impact?

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [ ] I have added a matching `Type: XYZ` label to the PR

---

Fixes #7635

2021-05-21 17:05 UTC, samwhale approved these changes

2021-05-21 17:23 UTC, swissspidy approved these changes
You‘re fast!

2021-05-24 17:43 UTC, BrittanyIRL requested changes
Works well but I'm curious if you could adjust the spacing so that when there's no poster image to show the button lines up with the text as the poster would have? 

![Screen Shot 2021-05-24 at 10 43 33 AM](https://user-images.githubusercontent.com/10720454/119386815-e80c0300-bc7c-11eb-8be4-8f1a7216916c.png)

2021-05-24 17:45 UTC, BrittanyIRL approved these changes
Actually, nevermind  - we're doing more updates to the checklist in the next sprint and this'll change slightly.  

🚢

2021-05-25 16:16 UTC, merged