Bug: PPCv2.0 Checklist Panel Focus Border
GoogleForCreators/web-stories-wp pull request #8225
Opened 2021-07-07 16:37 UTC by littlemilkstudio

## Context
Small style bug fix for focus styles in the PPCv2.0

## Summary
Allows full focus border for the tablists to be visible within PPCv2.0.

**Before**
![124328235-7a3ddb80-db46-11eb-8a04-e98b9ce2f5b7](https://user-images.githubusercontent.com/35983235/124796500-da51ca80-df16-11eb-8edb-fdfedf703730.gif)

**After**
https://user-images.githubusercontent.com/35983235/124796208-85ae4f80-df16-11eb-9766-d5fdc692a6b1.mp4

## Relevant Technical Choices
Just shrank the button a bit and spoofed the bg so that focus border fits within the space and the button has no visual discrepancies from before

## To-do
NA

## User-facing changes
Focus styles when using keyboard should now be fully visible on the tablist button here.

## Testing Instructions
Enable PPC companion in experiments and keyboard navigate onto the open state of it. Should now see full focus border when focused on a tablist button component. Reference screenshots above if needed.

### QA
- Go to Experiments
- Enable the editor check: `Enable Checklist Companion`
- Open an existing story or create a new one in the editor
- Ensure there's at least 5 pages and some content so the Prepublish checklist checks start populating
- use your keyboard to navigate into the Prepublish checklist
- Tab between check categories and see that the full focus border is visible like in the `After` screencasts above

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [x] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Reviews

### Does this PR have a security-related impact?

### Does this PR change what data or activity we track or use?

### Does this PR have a legal-related impact?

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [ ] I have added a matching `Type: XYZ` label to the PR

---

Fixes #8175

2021-07-07 16:49 UTC, BrittanyIRL commented on assets/src/edit-story/components/tablist/tablistPanel.js
> +            /* translators: %d: number of issues, %s: title */
Pascal improved this in #8212 (https://github.com/google/web-stories-wp/pull/8212/files#diff-19a042f78fb750578fdbbfb643e3051db5b609aef6d8281ce220a1c610a7d75a) with 
` /* translators: 1: number of issues. 2: type of issue, for example "High Priority". */` - just a heads up to make sure that change sticks

2021-07-07 16:56 UTC, BrittanyIRL requested changes
this is greatly improved! good idea to fix this. 

It seems that the border is still incomplete on the final panel button when there is an expanded panel above. 
<img width="390" alt="Screen Shot 2021-07-07 at 9 55 31 AM" src="https://user-images.githubusercontent.com/10720454/124799593-960bfd80-df09-11eb-947a-846b296700a1.png">
<img width="349" alt="Screen Shot 2021-07-07 at 9 55 14 AM" src="https://user-images.githubusercontent.com/10720454/124799598-96a49400-df09-11eb-8e68-14c83d531c16.png">

2021-07-08 17:59 UTC, BrittanyIRL approved these changes
Perfect!

2021-07-08 18:13 UTC, embarks approved these changes
Works great :D

2021-07-14 16:03 UTC, samwhale approved these changes
This looks super dope. Would it be too much to ask for a quick update to change the focus color from `primary` to `secondary`?

Here we need it when it's collapsed:
![image](https://user-images.githubusercontent.com/22185279/125653894-71ae9fec-eef7-45fb-a799-732f2e27572e.png)

Here we need it for the cards:
![image](https://user-images.githubusercontent.com/22185279/125653851-bea732d9-d71e-4579-85bb-fc9170d75b6c.png)

2021-07-14 19:01 UTC, samwhale commented
@googlebot I consent.

2021-07-14 19:02 UTC, samwhale commented
> This looks super dope. Would it be too much to ask for a quick update to change the focus color from `primary` to `secondary`?

Just added those updates. Now the focus looks like a blue ring without that black border:

<img src="https://user-images.githubusercontent.com/22185279/125677869-0008aca2-4cef-47b4-b3ef-dba2fafe077d.gif" height="400px" />

2021-07-21 18:47 UTC, merged