Settings: Optimize publisher logos image sizes
GoogleForCreators/web-stories-wp pull request #8273
Opened 2021-07-09 19:57 UTC by littlemilkstudio

## Context
Looked into utilizing srcsets, but there's no smaller sizes for logo resources available beyond what the user uploads

## Summary
Just sets the publisher logo size to 96x96 px in the settings view to make it more consistent with AMP recommendations.

## Relevant Technical Choices
NA

## To-do
NA

## User-facing changes
Logos should be slightly larger in the settings page.

## Testing Instructions
- Go to settings
- See that the Publisher logo thumbnails are 96x96 px

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [ ] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Reviews

### Does this PR have a security-related impact?

### Does this PR change what data or activity we track or use?

### Does this PR have a legal-related impact?

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [ ] I have added a matching `Type: XYZ` label to the PR

---

Fixes #4816

2021-07-09 21:25 UTC, swissspidy commented
From the ticket:

> Let's set explicit width and height attributes on the img

I think we can still do that. Helps prevent layout shifts.

2021-07-12 09:48 UTC, spacedmonkey commented
Related https://github.com/google/web-stories-wp/issues/7337 https://github.com/google/web-stories-wp/issues/4148

2021-07-13 00:20 UTC, BrittanyIRL approved these changes
👍

2021-07-13 09:15 UTC, swissspidy requested changes
Let's add `width` and `height` to the images

2021-07-13 19:18 UTC, littlemilkstudio commented
realized there's a 2px border around the images so the columns/rows need to be 100x100 to accommodate for that and allow the image to be 96x96

2021-07-14 08:51 UTC, swissspidy commented on assets/src/dashboard/app/views/editorSettings/components.js
> +  width: '96px',
```suggestion
  height: 96,
  width: 96,
```


These attributes are unit-less :-)

2021-07-14 08:55 UTC, swissspidy commented
> realized there's a 2px border around the images so the columns/rows need to be 100x100 to accommodate for that and allow the image to be 96x96

There's also a 1px border on `GridItemContainer`, so the image is now actually displayed at 94x94px

![Screenshot 2021-07-14 at 10 52 21](https://user-images.githubusercontent.com/841956/125593926-0e201e6a-2bb9-490a-aa89-0eed8cced168.png)

2021-07-14 08:56 UTC, swissspidy commented on assets/src/dashboard/app/views/editorSettings/components.js
> +  grid-auto-rows: 100px;
```suggestion
  grid-template-columns: repeat(auto-fill, 102px);
  grid-auto-rows: 102px;
```

To accommodate for the other border as well so images are actually displayed at 96x96

2021-07-19 12:44 UTC, swissspidy approved these changes

2021-07-19 12:44 UTC, merged