Remove Duplicate Icons
GoogleForCreators/web-stories-wp pull request #8668
Opened 2021-08-12 13:14 UTC by g-sqiao

## Context

Replaced the original pencil icon with the one in design-system.

## Summary

## Relevant Technical Choices

## To-do

## User-facing changes

## Testing Instructions

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [ ] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Reviews

### Does this PR have a security-related impact?

### Does this PR change what data or activity we track or use?

### Does this PR have a legal-related impact?

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [ ] I have added a matching `Type: XYZ` label to the PR

---

Fixes #

2021-08-13 18:57 UTC, BrittanyIRL requested changes
| This PR | Main | 
| --- | --- | 
| ![Screen Shot 2021-08-13 at 11 36 52 AM](https://user-images.githubusercontent.com/10720454/129405268-1599172e-9114-41bd-b9f3-282f1856b80e.png) | ![Screen Shot 2021-08-13 at 11 37 08 AM](https://user-images.githubusercontent.com/10720454/129405276-a5305317-abe5-4994-a705-f57292c93675.png) | 

See the difference in size? 

So, with the SVGs to properly replace them you're going to have to adjust the size of a few things because the [SVG viewbox](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox) is different. You can see this if you open dev tools and inspect the edit icon in the button. 

Additionally, here the button isn't using the one in the design system and it probably could use the icon variant. 

Not to be pedantic, but screen shots of the changes are incredibly helpful. The PR description has a template built into it so that context and review are easier to glean. It would be useful to update that here. 

Thanks!

2021-08-16 16:59 UTC, choumx commented on packages/dashboard/src/app/views/editorSettings/publisherLogo/popoverLogoContextMenu.js
> -import { EditPencil as EditPencilIcon } from '../../../../icons';
Should we also remove `EditPencil` from this `icons.js`?

2021-08-16 16:59 UTC, choumx commented on packages/dashboard/src/icons/editPencil.svg
> -<svg fill="none" height="12" width="13" viewBox="0 0 13 12" width="13" xmlns="http://www.w3.org/2000/svg">
This file should be removed, no?

2021-08-16 17:00 UTC, choumx commented
> screen shots of the changes are incredibly helpful. The PR description has a template built into it so that context and review are easier to glean. It would be useful to update that here.

+1, ditto for the other PRs.

2021-08-16 22:29 UTC, BrittanyIRL reviewed
hi again! 

So i get that this is confusing and it was probably a kind of chaotic place to start 😂  I took some time and figured out how to swap this out. I'm going to lay it out here for you so that you can get more comfortable with the codebase. 


Open `dashboard/srcs/app/views/editorSettings/components.js`.
This is where all of the styled components live that make up the settings page. We're going to go look at the `LogoMenuButton` (should be about line 171).

Right off the bat, we can see that this "button" is not using the [`Button` component from the design system](https://google.github.io/web-stories-wp/storybook/?path=/story/designsystem-components-button--light-theme), so let's swap that out. We know we want it to be round (`BUTTON_VARIANTS.CIRCLE`) and based on looking at the rest of the page as well as the theme colors, we know that this button is the "wrong" (outdated) color. So let's make it a secondary button. You can also see that the "small" buttons are a smidge larger than these lil itty bitty ones, so let's ditch the custom styles in favor of continuity with the design system. You'll end up with a base that looks like this: 

```
export const LogoMenuButton = styled(Button).attrs({
  size: BUTTON_SIZES.SMALL,
  type: BUTTON_TYPES.SECONDARY,
  variant: BUTTON_VARIANTS.CIRCLE,
})
```

Now we're enabled to delete a bunch of lines that were making this custom button. You should be able to remove the following: 
```
  display: flex;
  align-items: center;
 width: 24px;
  height: 24px;
  text-align: center;
  padding: 0;
  color: ${({ theme }) => theme.colors.standard.white};
  background: ${({ theme }) => theme.colors.fg.secondary};
  border-radius: 50%;
  border: 1px solid transparent;
  cursor: pointer;
```

Now we have a pretty, consistent, round button. It should look like this: 
```
export const LogoMenuButton = styled(Button).attrs({
  size: BUTTON_SIZES.SMALL,
  type: BUTTON_TYPES.SECONDARY,
  variant: BUTTON_VARIANTS.CIRCLE,
})`
  opacity: ${({ isActive, menuOpen }) => (menuOpen || isActive ? 1 : 0)};
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
`
```

Next, let's do the icon. First, go delete the editPencil icon that you edited in `packages/dashboard/src/icons/editPencil.svg` 😅 ! Now, go to `editorSettings/publisherLogoContextMenu.js` and import `Icons` from the design-system (already listed at the top of external imports) and replace the `<EditPencilIcon />` with `<Icons.Pencil />`.

Go back to the `LogoMenuButton` styles and let's look at the svg styles getting applied. So, the old icon needed a bunch of stuff applied to it because of how the size was of the svg. The viewbox and the width were making it a little lopesided, super fun when you're trying to center something.  For comparison, the SVG we're deleting was ` height="12" width="13" viewBox="0 0 13 12" width="13"` and the new one is `width="32" height="32" viewBox="0 0 32 32"`.

The great news here is that we need **none** of that customization. Just delete it. If you're curious. Open your dev tools and inspect the SVG, see the styles applied to it and remove the styles by clicking the checkbox next to the styles one by one and see it get better. 

You should be able to end up with this code for the entire button: 
```
export const LogoMenuButton = styled(Button).attrs({
  size: BUTTON_SIZES.SMALL,
  type: BUTTON_TYPES.SECONDARY,
  variant: BUTTON_VARIANTS.CIRCLE,
})`
  opacity: ${({ isActive, menuOpen }) => (menuOpen || isActive ? 1 : 0)};
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
`;
```

| Code above | Staging | 
| --- | --- | 
|  <img width="122" alt="Screen Shot 2021-08-16 at 3 18 52 PM" src="https://user-images.githubusercontent.com/10720454/129636776-cd2f79c6-5e5c-4c46-9986-26ff4b9c4be2.png"> |  <img width="106" alt="Screen Shot 2021-08-16 at 3 05 10 PM" src="https://user-images.githubusercontent.com/10720454/129636788-18d18847-acc7-4685-a769-b79932cfe03f.png"> | 


Does this make sense?

2021-08-16 23:06 UTC, g-sqiao commented
> hi again!
> 
> So i get that this is confusing and it was probably a kind of chaotic place to start 😂 I took some time and figured out how to swap this out. I'm going to lay it out here for you so that you can get more comfortable with the codebase.
> 
> Open `dashboard/srcs/app/views/editorSettings/components.js`.
> This is where all of the styled components live that make up the settings page. We're going to go look at the `LogoMenuButton` (should be about line 171).
> 
> Right off the bat, we can see that this "button" is not using the [`Button` component from the design system](https://google.github.io/web-stories-wp/storybook/?path=/story/designsystem-components-button--light-theme), so let's swap that out. We know we want it to be round (`BUTTON_VARIANTS.CIRCLE`) and based on looking at the rest of the page as well as the theme colors, we know that this button is the "wrong" (outdated) color. So let's make it a secondary button. You can also see that the "small" buttons are a smidge larger than these lil itty bitty ones, so let's ditch the custom styles in favor of continuity with the design system. You'll end up with a base that looks like this:
> 
> ```
> export const LogoMenuButton = styled(Button).attrs({
>   size: BUTTON_SIZES.SMALL,
>   type: BUTTON_TYPES.SECONDARY,
>   variant: BUTTON_VARIANTS.CIRCLE,
> })
> ```
> 
> Now we're enabled to delete a bunch of lines that were making this custom button. You should be able to remove the following:
> 
> ```
>   display: flex;
>   align-items: center;
>  width: 24px;
>   height: 24px;
>   text-align: center;
>   padding: 0;
>   color: ${({ theme }) => theme.colors.standard.white};
>   background: ${({ theme }) => theme.colors.fg.secondary};
>   border-radius: 50%;
>   border: 1px solid transparent;
>   cursor: pointer;
> ```
> 
> Now we have a pretty, consistent, round button. It should look like this:
> 
> ```
> export const LogoMenuButton = styled(Button).attrs({
>   size: BUTTON_SIZES.SMALL,
>   type: BUTTON_TYPES.SECONDARY,
>   variant: BUTTON_VARIANTS.CIRCLE,
> })`
>   opacity: ${({ isActive, menuOpen }) => (menuOpen || isActive ? 1 : 0)};
>   position: absolute;
>   top: 50%;
>   left: 50%;
>   transform: translate(-50%, -50%);
> `
> ```
> 
> Next, let's do the icon. First, go delete the editPencil icon that you edited in `packages/dashboard/src/icons/editPencil.svg` 😅 ! Now, go to `editorSettings/publisherLogoContextMenu.js` and import `Icons` from the design-system (already listed at the top of external imports) and replace the `<EditPencilIcon />` with `<Icons.Pencil />`.
> 
> Go back to the `LogoMenuButton` styles and let's look at the svg styles getting applied. So, the old icon needed a bunch of stuff applied to it because of how the size was of the svg. The viewbox and the width were making it a little lopesided, super fun when you're trying to center something. For comparison, the SVG we're deleting was ` height="12" width="13" viewBox="0 0 13 12" width="13"` and the new one is `width="32" height="32" viewBox="0 0 32 32"`.
> 
> The great news here is that we need **none** of that customization. Just delete it. If you're curious. Open your dev tools and inspect the SVG, see the styles applied to it and remove the styles by clicking the checkbox next to the styles one by one and see it get better.
> 
> You should be able to end up with this code for the entire button:
> 
> ```
> export const LogoMenuButton = styled(Button).attrs({
>   size: BUTTON_SIZES.SMALL,
>   type: BUTTON_TYPES.SECONDARY,
>   variant: BUTTON_VARIANTS.CIRCLE,
> })`
>   opacity: ${({ isActive, menuOpen }) => (menuOpen || isActive ? 1 : 0)};
>   position: absolute;
>   top: 50%;
>   left: 50%;
>   transform: translate(-50%, -50%);
> `;
> ```
> 
> Code above	Staging
> <img alt="Screen Shot 2021-08-16 at 3 18 52 PM" width="122" src="https://user-images.githubusercontent.com/10720454/129636776-cd2f79c6-5e5c-4c46-9986-26ff4b9c4be2.png">	<img alt="Screen Shot 2021-08-16 at 3 05 10 PM" width="106" src="https://user-images.githubusercontent.com/10720454/129636788-18d18847-acc7-4685-a769-b79932cfe03f.png">
> Does this make sense?

OMG! You are AMAZING, Brittany!! <3 Thank you so much for the detailed explanations! LOL
Yup, it makes sense! Let me do the change and send it to you!

2021-08-16 23:25 UTC, g-sqiao commented
| After | Before | 
| --- | --- | 
| <img width="122" src="https://user-images.githubusercontent.com/14279973/129640746-e5a28a68-b959-4727-86c9-179f94dea605.png"> | <img width="122" src="https://user-images.githubusercontent.com/14279973/129641070-78b6af34-6d5e-4eff-9895-d43c11f667c7.png"> |

2021-08-16 23:35 UTC, BrittanyIRL approved these changes
👏 👏 👏  
Great job, thanks for stickin' with it.

I'm re-requesting @choumx for a secondary review and then this will go to QA.

2021-08-19 21:58 UTC, choumx approved these changes

2021-08-19 22:01 UTC, swissspidy commented
Great work! This now just needs some QA instructions for the affected areas to prevent regressions.

2021-08-24 16:46 UTC, swissspidy commented
@BrittanyIRL could you perhaps help with QA instructions here?

2021-08-25 23:44 UTC, BrittanyIRL commented
(I see the conflict and will fix first thing in AM)

2021-08-26 23:11 UTC, merged