Output: Fix malformed `<a>` tags in the `<head>`
GoogleForCreators/web-stories-wp pull request #9298
Opened 2021-10-06 13:54 UTC by swissspidy

## Context

There can be some mangled `<script>` tags turned into `<a>` on WP.com VIP.

## Summary

This PR detects incorrect `<a>` tags in the HTML output and turns them into actual `<script>` tags as expected.

## Relevant Technical Choices

Since it is **not** possible to fix this with the sanitizers, and since the root cause with the KSES logic is unclear, this workaround lives in the `HTML` class on purpose.

## To-do

- Testing

## User-facing changes

N/A

## Testing Instructions

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. TBD

## Reviews

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #9297

2021-10-06 15:02 UTC, spacedmonkey commented on includes/Renderer/Story/HTML.php
> +		$markup = $this->fix_malformed_script_link_tags( $markup );
Could we maybe only conditionally run this logic. Like checking for `VIP_GO_ENV` const. [See](https://github.com/Automattic/vip-go-mu-plugins/blob/291e8d413545ccc6a537e9415bc7e9ebce543e4e/000-vip-init.php#L83-L94).

2021-10-06 17:12 UTC, swissspidy commented on includes/Renderer/Story/HTML.php
> +		$markup = $this->fix_malformed_script_link_tags( $markup );
While I have only encountered this on VIP sites so far, it doesn't mean that it can't happen on other environments as well.

So I don't want to run this conditionally. There's no harm in always running this, performance-wise the impact should be minimal, the regex is pretty lightweight.

2021-10-07 12:02 UTC, swissspidy commented
I've sent this to the partner for review and will provide an update once I know whether it works as expected.

2021-10-08 14:12 UTC, swissspidy commented
Got confirmation that it works as expected! 🎉

2021-10-08 14:13 UTC, swissspidy commented on includes/Renderer/Story/HTML.php
> +		$markup = $this->fix_malformed_script_link_tags( $markup );
Just got confirmation that it was reproducible outside of the WPCOMVIP environment. So definitely not going to run this conditionally.

2021-10-11 09:39 UTC, spacedmonkey requested changes
There are two PHPCS lint warnings I would like to see fixed before approving this.

2021-10-11 09:57 UTC, swissspidy commented
> There are two PHPCS lint warnings I would like to see fixed before approving this.

Those are just false positives that I now ignored.

Also weird that these are just warnings and not errors causing the check to fail 🤔

2021-10-11 16:17 UTC, spacedmonkey approved these changes

2021-10-11 16:29 UTC, merged