Move Calendar to floating sidebar
GoogleForCreators/web-stories-wp pull request #935
Opened 2020-04-01 12:15 UTC by miina

Fixes #788 

Moves calendar to the floating sidebar and reworks `useSidebar` to not depend on the components that are rendered in the content.

2020-04-01 12:23 UTC, miina commented on assets/src/edit-story/components/sidebar/provider.js
> -import ColorPicker from '../../components/colorPicker';
@barklund -- Changed the logic of Sidebar in this PR so that it wouldn't have to be aware of the content that's displayed in it, PTAL.

2020-04-01 13:09 UTC, swissspidy approved these changes
LGTM from my side. Deferring to @barklund for reviewing changes to sidebar provider

2020-04-01 18:03 UTC, miina commented
Note that there is currently a discussion on the calendar still needing to be directly under the field and just not having to be contained in the sidebar but always being on top of everything:
https://github.com/google/web-stories-wp/issues/788#issuecomment-607378855

Likely this will need some reworking again unless we'd want to merge it as-is to alpha and follow up ASAP in a separate PR.

2020-04-01 18:13 UTC, barklund requested changes
Looks good - just a few structural and a11y comments.

2020-04-01 18:13 UTC, barklund commented on assets/src/edit-story/components/form/color/test/colorPreview.js
> +      expect.any(Function)
Hm, this now doesn't validate, that the color picker to be opened will receive the right props.

Can we mock out the color picker with a dummy component, and verify that this dummy component is created with the right props?

2020-04-01 18:13 UTC, barklund commented on assets/src/edit-story/components/inspector/document/publish/index.js
> +  const displayCalendar = useCallback(() => {
When displayed, focus should be moved to the first input inside the date picker (the date input field).

2020-04-01 18:13 UTC, barklund commented on assets/src/edit-story/components/inspector/document/publish/index.js
> +      if (close) {
The date picker should be dismissible using the esc key and when pressed, keyboard focus should be returned to where it came from (the date form field in the inspector).

2020-04-01 18:13 UTC, barklund commented on assets/src/edit-story/components/inspector/document/publish/index.js
>          <FieldLabel>{__('Publish', 'web_stories')}</FieldLabel>
I think clicking this label should also show the date picker. In general our labels should focus the input fields and/or simulate when happens when clicking the corresponding input field.

2020-04-01 18:13 UTC, barklund commented on assets/src/edit-story/components/inspector/document/publish/index.js
> +          aria-expanded={hasSidebar}
Expanded? It's not really expanded, is it?

Also, the icon doesn't actually change to an up arrow, so maybe the arrow icon should be completely removed now?
![Screen Shot 2020-04-01 at 2 02 41 PM](https://user-images.githubusercontent.com/637548/78171231-2a8fd200-7422-11ea-905f-68d55291d32c.png)

2020-04-01 18:13 UTC, barklund commented on assets/src/edit-story/components/inspector/document/test/publish.js
> +      expect.any(Function)
Also here I'd like to see at least some validation, that the right thing is displayed. This will have many false positives.

2020-04-01 18:13 UTC, barklund commented on assets/src/edit-story/components/sidebar/provider.js
> +  const showSidebarAt = useCallback((node, displayContent) => {
Rename it to `renderContent` - that'll make it more transparent as a render prop style structure.

2020-04-01 18:13 UTC, barklund commented on assets/src/edit-story/components/sidebar/provider.js
> +              {sidebarState.displayContent && sidebarState.displayContent()}
Preferably destruct this above as `const { renderContent } = sidebarState;` and then just assume it to be defined as a function here with `{renderContent()}`.

If it's not a function, it should fail hard anyway! No need to show a sidebar with no content.

2020-04-01 18:14 UTC, barklund commented on assets/src/edit-story/components/inspector/document/publish/index.js
> +          aria-expanded={hasSidebar}
Maybe change the arrow to a calendar icon, if we have one such? Tagging in @samitron7 here.

2020-04-02 11:21 UTC, spacedmonkey commented
Should the arrow change direction when clicked. See https://material-components.github.io/material-components-web-catalog/#/component/select

2020-04-03 07:45 UTC, miina commented
Closing as superseded by #986

2020-04-03 07:45 UTC, closed without merging