Fix: Media Accessibility Panel UI Simplifications
GoogleForCreators/web-stories-wp pull request #9488
Opened 2021-10-21 11:13 UTC by delowardev

See: #9465

## Context

Media Accessibility Panel UI Simplifications

## Summary

Added description above the textarea for both Video and Image (instead of the current placeholder). 
See: [figma](https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor---Sprint-Feature-Level-Designs_?node-id=10250%3A436662)

## Relevant Technical Choices

## To-do

 - [x] Accessibility panel: Add description above the textarea for both Video and Image (instead of the current placeholder).
 - [x] Filter Panel: Add eyedropper next to the Color input (not seen in Figma but it was confirmed by UX that it should be like this everywhere. Makes sense to add it to the Color input directly if not done elsewhere.

## User-facing changes

Description moved to the label from placeholder.

Before | After
---|---
<img src="https://i.imgur.com/h6KPx3M.png" alt="alt text" width="300" height="auto" />|<br/> <img src="https://i.imgur.com/9WoshUg.png" alt="alt text" width="300" height="auto" />
<img src="https://i.imgur.com/OSZiJET.png" alt="alt text" width="300" height="auto" />|<br/><img src="https://i.imgur.com/zk4XxJp.png" alt="alt text" width="300" height="auto" />
<img src="https://i.imgur.com/AlcwgKT.png" alt="alt text" width="300" height="auto" />|<img src="https://i.imgur.com/z0d1eZt.png" alt="alt text" width="300" height="auto" />
<br/>

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

Important! From Pascal: FYI 3P PRs are not uploaded for QA due to GHA limitations. One would need to download the ZIP file from https://github.com/google/web-stories-wp/runs/4011337300 and install that version manually.

1. Add media (test with both image and video)
2. Open the Filter Panel, verify that in case of "Tint", eyedropper is displayed next to the Color Picker and it works as expected. There should be no eyedropper for Linear / Vignette.
3. Verify the style of the eyedropper looks as in [Figma ](https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor---Sprint-Feature-Level-Designs_?node-id=10291%3A442662)
4. Open the Accessibility panel. Verify the description of the Accessibility field is displayed above the textarea for both Video and Image
5. Verify the design matches [Figma](https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor---Sprint-Feature-Level-Designs_?node-id=10250%3A436662)

## Reviews

### Does this PR have a security-related impact?

### Does this PR change what data or activity we track or use?

### Does this PR have a legal-related impact?

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #9465

2021-10-21 11:23 UTC, miina commented on packages/story-editor/src/components/panels/design/imageAccessibility/imageAccessibility.js
> +          label={__(
As it is now, it's not really a label and is more of a description/hint. Ideally all text area components should work the same way and have consistent UX.
I'll confirm this with UX team, it might still change a bit.

2021-10-22 15:56 UTC, delowardev commented on packages/story-editor/src/components/panels/design/imageAccessibility/imageAccessibility.js
> +          label={__(
Added as a separate text similar to the "Story Description in the Document panel" as you mentioned

2021-10-25 06:32 UTC, delowardev commented
@miina could you please confirm how Eyedropper should behave when it's with gradient picker?

![](https://i.imgur.com/HyR9SmJ.png)

2021-10-25 08:38 UTC, miina commented
> could you please confirm how Eyedropper should behave when it's with gradient picker?

@delowardev We have the eyedropper feature currently implemented in the Color Picker -- we should just reuse the feature from there (Opening the Color Picker -> Clicking "Custom" button will open the custom view of the Color Picker where Eyedropper is). When using the Eyedropper, it chooses a new color from the Page and overwrites the existing one, so the previous color being gradient is irrelevant.

2021-10-25 08:41 UTC, miina commented on packages/story-editor/src/components/form/color/color.js
> +import useEyedropper from '../../colorPicker/eyedropper';
Since the eyedropper will now mostly used outside of the `colorPicker`, it might make sense to separate it from the `colorPicker` component.

2021-10-25 08:43 UTC, miina commented on packages/story-editor/src/components/form/color/color.js
> +// extra 2% width to fit color input when eyedropper is enabled
The width of the panel is dynamic (changes depending on the screen width), however, the size of the Eyedropper button is always the same, so probably the extra room the eyedropper button should be considered in pixels, as it's static. Where did the 2% come from?

2021-10-25 08:44 UTC, miina commented on packages/story-editor/src/components/form/color/color.js
> +    themeHelpers.focusableOutlineCSS(theme.colors.border.focus, '#1d1f20')};
Would just `${focusStyle};` not work here?

2021-10-25 08:45 UTC, miina commented on packages/story-editor/src/components/panels/design/filter/filter.js
> -        <Row>
Why remove the Row from here?

2021-10-25 08:49 UTC, miina commented
> could you please confirm how Eyedropper should behave when it's with gradient picker?

Ah, okay, now I understand, this question is for the Linear and Vignette specifically. We can disable the Eyedropper for these cases for now -- I'll check with UX and we can follow up about this if needed.

2021-10-25 10:29 UTC, delowardev commented on packages/story-editor/src/components/form/color/color.js
> +// extra 2% width to fit color input when eyedropper is enabled
Here the problem is with color input itself, it requires a minimum of 106px to display properly (hex value in the left image), so fixed with `flex-basis & flex-grow`.

![](https://i.imgur.com/mfY8gMu.jpg)

2021-10-25 10:45 UTC, miina commented on packages/story-editor/src/components/form/color/color.js
>  const InputWrapper = styled.div`
From Figma, it looks like the Opacity input is always generally shorter than the Hex input, e.g. 100px vs 113px [here](https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor---Sprint-Feature-Level-Designs_?node-id=10250%3A435845).

Previously, Opacity input did not have an icon and had `Opacity` written out, that's why it needed the same amount of room as the Hex input. Now that it only has an icon, we could always display it a little bit narrower compared to the Hex input, not only when the Eyedropper is present. E.g. using the 100px vs 113px in Figma would be 47% and 53% (- divider), we could always use these values now (as in Figma), this will also reduce the empty space of the opacity field a bit.
Thoughts?

2021-10-25 11:11 UTC, delowardev commented on packages/story-editor/src/components/form/color/color.js
>  const InputWrapper = styled.div`
Right, it would simply resolve that issue.

2021-10-26 09:06 UTC, miina commented
@delowardev Let me know if the PR is ready for review (or re-request a review from me). I saw you marked it ready for review but also added some new commits, so not sure if it's currently just waiting for review.

2021-10-26 09:38 UTC, miina requested changes

2021-10-26 09:38 UTC, miina commented on packages/story-editor/src/components/form/color/color.js
> +  margin-right: 4px;
The space in Figma is 8px, let's use the same as in Figma.

2021-10-26 09:38 UTC, miina commented on packages/story-editor/src/components/form/color/color.js
> +  const withEyedropper = (children) => {
Q: Why use the wrapper of `withEyedropper` here instead of just adding `<Tooltip>...</Tooltip>` directly before the `InputWrapper` below?

2021-10-26 09:38 UTC, miina commented on packages/story-editor/src/components/form/color/color.js
> +    value.type !== OverlayType.RADIAL &&
Detecting this part should go directly to the Filter panel and `hasEyedropper` not be added if it's radial/linear. Filter panel is the only place where we should avoid displaying the Eyedropper for non-solid colors.

In other cases, the eyedropper value would just overwrite the previous color.

2021-10-26 09:38 UTC, miina commented on packages/story-editor/src/components/panels/design/imageAccessibility/imageAccessibility.js
> +  color: ${({ theme }) => theme.colors.fg.tertiary};
Should be `theme.colors.fg.secondary` per Figma:
<img width="247" alt="Screenshot 2021-10-26 at 12 33 41" src="https://user-images.githubusercontent.com/3294597/138851741-2eaa8172-f51b-474d-bb42-bb27ac65f89c.png">

2021-10-26 09:38 UTC, miina commented on packages/story-editor/src/components/panels/design/imageAccessibility/imageAccessibility.js
> +  margin-bottom: 12px;
I'm seeing 10px in Figma, which place did you see 12px? Mb I'm checking other place.

2021-10-26 09:38 UTC, miina commented on packages/story-editor/src/components/panels/design/videoAccessibility/videoAccessibility.js
> +  color: ${({ theme }) => theme.colors.fg.tertiary};
Same here about the color, it's marked `secondary` in Figma.

2021-10-26 10:21 UTC, delowardev commented on packages/story-editor/src/components/form/color/color.js
> +  margin-right: 4px;
@miina in 4px is being used in the "Text panel", couldn't find a focused/hover style for the EyeDropper button in Figma.

<img src="https://i.imgur.com/8wfepPT.png" width="400" />

2021-10-26 10:26 UTC, delowardev commented on packages/story-editor/src/components/form/color/color.js
> +  const withEyedropper = (children) => {
@miina  Just wanted to avoid CSS calculation for the EyeDropper & its margin, thought it would be less confusing to wrap with the container. Do you prefer adding before the `InputWrapper` instead? (the CSS `calc` would be something like `(53% - (eyeDropper + margin / 2) - divider)`

2021-10-26 10:27 UTC, miina commented on packages/story-editor/src/components/form/color/color.js
> +  margin-right: 4px;
@delowardev Let's use 8px as in Figma for the eyedropper:
<img width="162" alt="Screenshot 2021-10-26 at 13 25 32" src="https://user-images.githubusercontent.com/3294597/138860120-6810f369-4040-474e-8de9-c16c0ee4e570.png">

The focus/hover style comes automatically from the button type (tertiary), so no need to worry about that.

2021-10-26 10:30 UTC, miina commented on packages/story-editor/src/components/form/color/color.js
> +  const withEyedropper = (children) => {
If it makes sense, you can still wrap the eyedropper button into a `EyedropperWrapper` or something similar, just not sure why it needs to be using `withEyedropper` instead of just adding it before the `InputWrapper`

2021-10-26 11:11 UTC, delowardev commented on packages/story-editor/src/components/panels/design/imageAccessibility/imageAccessibility.js
> +  margin-bottom: 12px;
updated to 10px. I think there are some design mismatches in the Figma, for example: [here](https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor---Sprint-Feature-Level-Designs_?node-id=10149%3A434319) the margin is 6px

2021-10-26 11:47 UTC, miina commented on packages/story-editor/src/components/panels/design/imageAccessibility/imageAccessibility.js
> +  margin-bottom: 12px;
That Figma area is outdated, only the area that's linked in the issue is up to date -- the area that has the latest date (10/12-15)

2021-10-26 12:26 UTC, miina commented on packages/story-editor/src/components/form/color/color.js
> +  width: ${({ hasEyedropper }) =>
Previously you mentioned having a wrapper around the `EyeDropperButton` to make this calculation more readable, any reason why you opted for not using it?

Probably the easiest way would be to have something like `ColorInputWrapper` around the color inputs and then `EyedropperWrapper` around the eyedropper button (if it needs one that all, maybe just having a wrapper around both color inputs would work as well). Then we could still just use `'calc(53% - 10px)'` etc., no?

Then it could be something like 
```
<Container>
  <Eyedropper ... />
  <ColorInputsWrapper>
    <InputWrapper ... />
    <OpacityWrapper ... />
  </ColorInputsWrapper>
</Container>
```

2021-10-26 12:27 UTC, miina commented on packages/story-editor/src/components/form/color/color.js
> +  width: ${({ hasEyedropper }) =>
(That's the last nit to look into, otherwise looks good)

2021-10-26 12:51 UTC, delowardev commented on packages/story-editor/src/components/form/color/color.js
> +  width: ${({ hasEyedropper }) =>
Thanks, that's a good idea actually. Code has been updated

2021-10-26 13:26 UTC, miina commented on packages/story-editor/src/components/form/color/color.js
> +  const ColorInputsWrapper = ({ children }) =>
Let's create a new styled component so that we always use it instead of displaying it conditionally.
The Container is currently a `section` tag, the wrapper around the input can be just a `div`.
```
  const ColorInputsWrapper = styled.div`...`;
```

2021-10-26 14:14 UTC, miina commented on packages/story-editor/src/components/form/color/color.js
> +const ContainerStyles = css`
Nit: for consistency with code elsewhere, let's use
`const containerCss = ...` (first char is lowercase + using Css as the suffix)

2021-10-26 14:20 UTC, miina commented on packages/story-editor/src/components/panels/design/imageAccessibility/imageAccessibility.js
> +        {__('Add assistive text for visually impaired users', 'web-stories')}
One more nit: in Figma, the new text is `Add a brief description of the image` ("video" in case of video)

2021-10-26 14:50 UTC, miina commented on packages/story-editor/src/components/panels/design/videoAccessibility/videoAccessibility.js
> +          <StyledText size={THEME_CONSTANTS.TYPOGRAPHY.PRESET_SIZES.X_SMALL}>
Just noticed that it's currently using `X_SMALL`. It's `SMALL` per Figma, using 14px as the font-size. 
X_SMALL uses 12px as the font size.

Let's change this to `SMALL` size instead.
<img width="234" alt="Screenshot 2021-10-26 at 17 48 56" src="https://user-images.githubusercontent.com/3294597/138904262-271217d7-99a0-4812-9a02-758b934c8776.png">

2021-10-26 15:57 UTC, miina approved these changes

2021-10-26 15:58 UTC, miina commented
@delowardev Thank you for working on the PR and for the quick responses!

2021-10-26 17:26 UTC, swissspidy commented
@miina @csossi FYI 3P PRs are not uploaded for QA due to GHA limitations. One would need to download the ZIP file from https://github.com/google/web-stories-wp/runs/4011337300 and install that version manually.

2021-11-01 10:09 UTC, merged