Template Layout panel: Tabbing Focus in FireFox
GoogleForCreators/web-stories-wp pull request #9623
Opened 2021-11-02 19:32 UTC by BrookeGraham

## Context

Keyboard navigation on Firefox was resulting in the template list to receive focus when tabbing from the filters dropdown to the actual template item. This meant an extra `Tab` was required to get from the filters dropdown to template. The same issue was found in the saved templates when going from the saved vs default dropdown to the actual template item. 

## Relevant Technical Choices

Removed `tabIndex` from template wrappers on both default templates and saved templates.

## To-do

## User-facing changes

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. In the editor, open the template layouts. 
2. Using keyboard navigation in FireFox `tab` through templates panel. 
2. Note focus should follow from filter dropdown arrow directly to the first template. 
3. Then check the focus follows the same pattern in Saved Templates from the `Saved Templates` dropdown directly to the first template. 

## Reviews

### Does this PR have a security-related impact?
no

### Does this PR change what data or activity we track or use?
no

### Does this PR have a legal-related impact?
no

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [ ] I have added a matching `Type: XYZ` label to the PR

---

Fixes #9554

2021-11-02 20:15 UTC, littlemilkstudio approved these changes
lgtm

2021-11-02 23:38 UTC, BrittanyIRL approved these changes
fixes it!  🚀

2021-11-03 13:04 UTC, samwhale requested changes
Working great in chrome and firefox but now I'm seeing the loss of focus borders in safari 😞 
![focus](https://user-images.githubusercontent.com/22185279/140064882-2cabec43-d4dd-45bb-9af8-20035fa29e6a.gif)

2021-11-04 15:16 UTC, BrookeGraham commented
@samwhale was version of Safari are you using? I am not seeing this issue. I am on `Version 15.0 (16612.1.29.41.4, 16612)`

https://user-images.githubusercontent.com/1820266/140345309-039e51ac-cd7c-43cb-98f1-8bb55007f4e9.mov

2021-11-04 16:26 UTC, samwhale commented
I'm using `Version 14.1.2 (16611.3.10.1.6)` - so maybe it's because of the older version? But if you're seeing that it works then that's all good for me 👍

2021-11-04 16:26 UTC, samwhale approved these changes

2021-11-04 16:27 UTC, merged